'use client';
import { useLang } from './lang';

// Traducciones del panel de administración (ES/EN).
// Un único diccionario; cada componente cliente llama useT() y usa t.clave.
// Los textos con número se arman en el componente combinando estas piezas.

const ES = {
  // Menú lateral
  brand: 'Onyx Admin',
  g_op: 'Operación', g_prod: 'Producto', g_growth: 'Crecimiento', g_sys: 'Sistema',
  nav_resumen: 'Resumen', nav_usuarios: 'Usuarios', nav_soporte: 'Soporte', nav_equipo: 'Equipo',
  nav_planes: 'Planes', nav_modulos: 'Módulos', nav_firms: 'Prop firms',
  nav_embajadores: 'Embajadores', nav_retencion: 'Retención',
  nav_kb: 'Base IA', nav_diag: 'Diagnóstico', nav_backups: 'Copias', nav_audit: 'Auditoría', nav_pruebas: 'Pruebas', nav_ajustes: 'Ajustes',
  avail_on: 'Disponible', avail_off: 'Ausente',
  h_backups_t: 'Copias de seguridad', h_backups_s: 'Protege los datos de los traders: exporta ahora o revisa el backup automático.',
  h_audit_t: 'Auditoría', h_audit_s: 'Velocidad, calidad y botones — probado solo en cada despliegue.',

  // Cabeceras de pestaña
  h_resumen_t: 'Resumen', h_resumen_s: 'El pulso del negocio y lo que necesita tu atención.',
  h_usuarios_t: 'Usuarios', h_usuarios_registered: 'registrados · busca y gestiona.',
  h_soporte_t: 'Soporte', h_soporte_s: 'Cola compartida — toma, responde, invita a un compañero.',
  h_equipo_t: 'Equipo y permisos', h_equipo_s: 'Añade miembros, asigna un rol y afina permisos por área.',
  h_equipo_s_ro: 'Solo quien gestiona el equipo puede cambiar roles.',
  h_planes_t: 'Planes', h_planes_s: 'Precios, funciones y capacidades reales de cada plan.',
  h_modulos_t: 'Módulos', h_modulos_s: 'Estado en vivo de las capacidades del sistema.',
  h_firms_t: 'Prop firms', h_firms_s: 'Plantillas que ve el trader al configurar límites. Corrige aquí y todos las ven.',
  h_embajadores_t: 'Embajadores', h_embajadores_s: 'Programa de referidos, comisiones y pagos.',
  h_retencion_t: 'Retención', h_retencion_s: 'Rescata a quien intenta irse y mide por qué.',
  h_kb_t: 'Base de conocimiento IA', h_kb_s: 'Lo que escribas aquí lo usa Onyx AI para responder, además de la Guía.',
  h_diag_t: 'Diagnóstico', h_diag_s: 'Salud del sistema y qué falta configurar.',
  h_pruebas_t: 'Consola de pruebas', h_pruebas_s: 'Simula lo que envía el EA, sin abrir MetaTrader: clave, límites y configuración de Onyx Guardian.',
  h_ajustes_t: 'Ajustes', h_ajustes_s: 'Tu rol, administradores y cómo se organiza el acceso.',

  // Resumen
  r_mrr: 'MRR estimado', r_paying: 'de pago', r_conversion: 'conversión',
  r_users: 'Usuarios', r_mtAccounts: 'cuentas MT', r_trades: 'operaciones',
  r_team: 'Equipo', r_availableNow: 'disponibles ahora', r_availableNow1: 'disponible ahora',
  r_banned: 'Baneados',
  r_needs: 'Necesita tu atención', r_allGood: 'Todo en orden', r_noPending: ' — sin pendientes por ahora.',
  r_sqlMissing: 'migración(es) SQL sin correr', r_seeDiag: 'Ver Diagnóstico',
  r_ticketsOpen: 'ticket(s) de soporte abierto(s)', r_openQueue: 'Abrir cola',
  r_svcConfig: 'servicio(s) por configurar', r_review: 'Revisar',
  r_bannedUsers: 'usuario(s) baneado(s)', r_seeUsers: 'Ver usuarios',

  // Usuarios (tabla)
  u_search: 'Buscar por email…', u_admin: 'admin',
  u_active: 'activo', u_banned: 'baneado',
  u_unban: 'Desbanear', u_makeAdmin: 'Hacer admin', u_removeAdmin: 'Quitar admin',

  // Equipo
  t_you: ' (tú)', t_lastActivity: 'Últ. actividad: ', t_noActivity: 'Sin actividad',
  t_perms: 'Permisos', t_close: 'Cerrar', t_remove: 'Quitar',
  t_permsByArea: 'Permisos por área', t_permsHint: '· el rol pone valores por defecto; aquí los afinas',
  t_invite: 'Invitar miembro (debe estar registrado en la app)',
  t_invitePh: 'email@ejemplo.com', t_inviteBtn: '+ Invitar',
  t_activity: 'Registro de actividad', t_member: 'Miembro:', t_all: 'Todos',
  t_noActivityTopic: 'Sin actividad en este tema.',
  lvl_none: 'Sin acceso', lvl_view: 'Ver', lvl_manage: 'Gestionar',
  role_owner: 'Owner', role_admin: 'Admin', role_support: 'Soporte', role_marketing: 'Marketing', role_custom: 'Personalizado',
  lt_all: 'Todos', lt_equipo: 'Equipo', lt_soporte: 'Soporte', lt_baseia: 'Base IA', lt_usuarios: 'Usuarios', lt_planes: 'Planes',

  // Soporte (helpdesk)
  s_open: 'Abiertos', s_inprogress: 'En curso', s_resolved: 'Resueltos', s_all: 'Todos',
  s_search: 'Buscar por correo o asunto…', s_empty: 'No hay conversaciones en esta vista.',
  s_pickOne: 'Elige una conversación de la izquierda para verla aquí.',
  s_unassigned: 'sin asignar', s_assignedTo: 'asignado a ',
  s_visitor: 'Visitante', s_inConvo: 'En la conversación: ',
  s_reply: 'Responder', s_note: 'Nota interna', s_notePh: 'Nota que solo ve el equipo…',
  s_replyPh: 'Respuesta para el trader (le llega por correo)…',
  s_sendReply: 'Enviar respuesta', s_saveNote: 'Guardar nota', s_aiDraft: 'Borrador IA',
  s_take: 'Tomar', s_resolve: 'Resolver', s_reopen: 'Reabrir',
  s_invitePh: 'Invitar compañero (su email de equipo)', s_inviteBtn: 'Invitar',
  st_open: 'Abierto', st_inprogress: 'En curso', st_resolved: 'Resuelto',
  sender_trader: 'Trader', sender_note: '🔒 Nota interna', sender_support: 'Soporte',
  ch_ticket: 'Ticket', ch_chat: 'Chat', ch_lead: 'Lead', ch_email: 'Email',
  cat_general: 'General', cat_conexion: 'Conexión', cat_instalacion: 'Instalación', cat_guardian: 'Onyx Guardian', cat_facturacion: 'Facturación',

  // Diagnóstico
  d_refresh: '↻ Refrescar', d_loading: 'Cargando diagnóstico…',
  d_quickTests: '⚡ Pruebas rápidas', d_testAI: '🤖 Probar IA', d_testEmail: '📧 Enviar correo de prueba', d_testTG: '✈️ Probar Telegram',
  d_db: '🗄️ Base de datos (¿corriste los SQL?)', d_applied: '✓ aplicado', d_missing: '✗ falta correr',
  d_missingMsg: 'Te falta correr en Supabase → SQL Editor: ',
  d_recentErrors: '🚨 Errores recientes', d_noErrors: 'Sin errores registrados. 🎉',
  d_commonErrors: '📖 Errores comunes explicados',

  // Ajustes
  a_yourRole: 'Tu rol', a_rolesTitle: 'Cómo funcionan los roles',
  a_rolesBody: 'El Owner controla planes, usuarios y equipo. Los Admin gestionan usuarios y planes. El Soporte solo consulta y ayuda.',
  a_rolesEnv: 'Los correos de ADMIN_EMAILS en Vercel siempre entran como Owner. Puedes añadir más administradores desde la pestaña Equipo.',

  // Módulos (cuerpo)
  mo_guardian_desc: 'Gestión de riesgo por EA en MT4 y MT5: break even, trailing, plan de trading, límites y noticias.',
  mo_guardian_accounts: 'cuentas con Guardian', mo_guardian_live: 'reportando ahora', mo_guardian_blocks: 'bloqueos ejecutados',
  mo_connected: 'Conectadas', mo_liveNow: 'En línea ahora', mo_withGuardian: 'Con Guardian', mo_blocks: 'Bloqueos',
  mo_tg_desc: 'Alertas del Guardian, límites de fondeo, EA caído y resumen del día. Comando /estado incluido.',
  mo_tg_linked: 'usuarios conectados', mo_active: 'Activo', mo_notoken: 'Sin token',
  mo_tg_connected: 'Conectados', mo_tg_sent7d: 'Enviados (7 d)', mo_tg_status: '/estado usados', mo_tg_failed: 'Fallidas',
  mo_rep_sent: 'Enviados', mo_rep_eligible: 'Elegibles', mo_rep_next: 'Próximo',
  mo_needLog: 'Algunas métricas necesitan la tabla telegram_log (corre el SQL). Empiezan en 0 y suben de verdad.',
  mo_liveBadge: 'En vivo', d_liveBadge: 'En vivo',
  mo_weekly_t: 'Informe semanal', mo_weekly_desc: 'Cada domingo, un informe del rendimiento de la semana por Telegram: resultado, aciertos, mejor par y disciplina.',

  // Planes (tarjeta)
  pl_count: 'Planes', pl_new: '+ Nuevo plan', pl_month: '$ / mes', pl_year: '$ / año',
  pl_es: '🇪🇸 ESPAÑOL', pl_en: '🇬🇧 ENGLISH', pl_caps: '🎛️ CAPACIDADES (control real)', pl_stripe: '💳 STRIPE',
  pl_id: 'id (pro)', pl_name: 'Nombre', pl_desc: 'Descripción corta', pl_badge: 'Etiqueta (ej. Más popular)', pl_features: 'Funciones (una por línea)',
  pl_nameEn: 'Name', pl_descEn: 'Short description', pl_badgeEn: 'Badge (e.g. Most popular)', pl_featuresEn: 'Features (one per line)',
  pl_mtAccounts: 'Cuentas MT', pl_historyDays: 'Días de historial', pl_unlimited: '(0 = ilimitado)',
  pl_priceIdM: 'Price ID mensual (price_...)', pl_priceIdY: 'Price ID anual (price_...)',
  pl_activeChk: 'Activo (visible en el landing y /pricing)',
  pl_create: 'Crear plan', pl_save: 'Guardar', pl_cancel: 'Cancelar', pl_delete: 'Borrar', pl_confirmDel: '¿Borrar el plan',
  cap_journal: 'Diario con fotos y notas', cap_compare: 'Comparar cuentas', cap_funding: 'Reglas de fondeo y retiros', cap_costs: 'Costes (comisión y swap)', cap_export: 'Exportar CSV', cap_reports: 'Informes automáticos', cap_telegram: 'Alertas por Telegram', cap_manager: 'Onyx Guardian: break even, trailing, plan y límites', cap_manager_advanced: 'Guardian avanzado: TP parciales', cap_manager_news: 'Guardian: bloqueo por noticias',

  // Prop firms
  fi_intro: 'Son el punto de partida que ve el trader al configurar sus límites. No son la norma oficial de ninguna firma: si una cambia sus reglas, corrígela aquí y todos los usuarios lo verán al instante. Los dos campos que más se equivocan son base de cálculo y hora de reinicio, por eso van siempre visibles.',
  fi_default: 'Ahora mismo se están usando las plantillas de fábrica.',
  fi_new: 'Nueva plantilla', fi_id: 'Identificador', fi_name: 'Nombre visible', fi_daily: 'Pérdida diaria %', fi_total: 'Pérdida total %',
  fi_base: 'Base de cálculo', fi_base1: 'Balance al empezar el día', fi_base2: 'Equity al empezar el día', fi_base3: 'Balance inicial',
  fi_reset: 'Hora de reinicio', fi_noteEs: 'Nota (ES)', fi_noteEn: 'Nota (EN)', fi_remove: 'Quitar',
  fi_confused: '⚠ Los 2 campos que más se equivocan', fi_daily_s: 'diaria', fi_total_s: 'total',
  fi_add: '+ Añadir plantilla', fi_save: 'Guardar', fi_resetBtn: 'Volver a las de fábrica', fi_saved: 'Guardado',
  fi_badPre: 'Hay', fi_bad: 'plantilla(s) sin identificador o sin nombre. Complétalas para poder guardar.',
  fi_confirmReset: '¿Volver a las plantillas de fábrica?',

  // Embajadores
  am_ambassadors: 'Embajadores', am_requests: 'Solicitudes', am_brought: 'Suscriptores traídos', am_toPay: 'Por pagar',
  am_payouts: 'Pagos solicitados', am_markPaid: 'Marcar pagado', am_reject: 'Rechazar',
  am_confirmPaid: '¿Confirmas que ya pagaste', am_rejectReason: 'Motivo del rechazo:',
  am_rules: '⚙️ Reglas del programa', am_baseRate: '% base', am_goldRate: '% nivel Oro', am_goldActive: 'Activos para Oro', am_holdDays: 'Días de retención',
  am_minPayout: 'Mínimo de retiro $', am_couponPct: '% del cupón', am_couponMonths: 'Meses del cupón',
  am_open: 'Programa abierto (acepta solicitudes y genera comisiones)', am_saveRules: 'Guardar reglas',
  am_couponNote: 'El % del cupón se aplica al aprobar nuevos embajadores. Los cupones ya creados no cambian.',
  am_list: 'Embajadores', am_empty: 'Todavía no hay solicitudes.',
  am_code: 'código', am_followers: 'seguidores',
  am_approve: 'Aprobar', am_pause: 'Pausar', am_reactivate: 'Reactivar',
  am_clicks: 'Clics', am_signups: 'Registros', am_active: 'Activos', am_conversion: 'Conversión',
  am_pending: 'Pendiente', am_available: 'Disponible', am_paid: 'Pagado',
  am_ownRate: 'Comisión propia:', am_ownRateHint: '% (vacío = por nivel)',
  am_gold: 'Oro', am_silver: 'Plata',
  st_pending: 'Pendiente', st_approved: 'Aprobado', st_rejected: 'Rechazado', st_paused: 'Pausado',
  am_promoFail: 'Aprobado, pero no se pudo crear el cupón en Stripe. Revisa tu clave de Stripe.',

  // Retención
  re_attempts: 'Intentos de baja', re_saved: 'Rescatados', re_lost: 'Perdidos', re_rate: 'Tasa de rescate',
  re_whyLeave: 'Por qué se quieren ir', re_noneYet: 'Todavía nadie ha intentado cancelar.',
  re_offers: '🛟 Ofertas de rescate', re_discPct: '% de descuento', re_discMonths: 'Meses del descuento', re_pauseMonths: 'Meses de pausa',
  re_allowDown: 'Ofrecer bajar a un plan más barato', re_flowOn: 'Flujo de retención activo', re_saveOffers: 'Guardar ofertas',
  re_extra: '➕ Cuentas MT extra', re_extraDesc: 'Crea en Stripe un precio recurrente mensual por unidad y pega aquí su Price ID. Sin él, el complemento no se muestra.',
  re_extraPrice: 'Precio por cuenta / mes ($)', re_extraId: 'Stripe Price ID', re_addonOn: 'Complemento activo', re_saveAddon: 'Guardar complemento',
  re_recent: 'Últimos intentos', re_recentEmpty: 'Nada por ahora.',
  reason_price: 'Muy caro', reason_unused: 'No lo usaba', reason_missing: 'Le falta algo', reason_stopped: 'Dejó de operar', reason_other: 'Otro',
  out_discount: 'Rescatado · descuento', out_pause: 'Rescatado · pausa', out_downgrade: 'Rescatado · bajó plan', out_canceled: 'Canceló', out_pending: 'Sin resolver',

  // Base IA (editor)
  kb_new: '+ Nuevo artículo', kb_intro: 'Lo que escribas aquí lo usa la IA para responder, además de la Guía. Ideal para precios, promociones, políticas o preguntas frecuentes que cambian.',
  kb_title: 'Título', kb_titlePh: 'Ej: ¿Ofrecen prueba gratis?', kb_body: 'Contenido (la respuesta)',
  kb_tags: 'Palabras clave (separadas por coma, ayudan a encontrarlo)', kb_tagsPh: 'prueba, gratis, demo, trial',
  kb_published: 'Publicado (la IA lo usa)', kb_save: 'Guardar', kb_cancel: 'Cancelar',
  kb_emptyEdit: 'Pon título y contenido.', kb_confirmDel: '¿Borrar este artículo de la base IA?',
  kb_empty: 'Aún no hay artículos. Crea el primero para que la IA sepa más.',
  kb_hidden: 'oculto', kb_hide: 'Ocultar', kb_publish: 'Publicar', kb_edit: 'Editar', kb_delete: 'Borrar',

  // Pruebas (consola)
  tc_myPlan: 'Mi plan de prueba', tc_myPlanDesc: 'Cámbiate de plan para probar los candados y Onyx Guardian. Es tu propia cuenta',
  tc_currentPlan: 'Plan actual', tc_of: 'de', tc_unlimited: 'ilimitadas', tc_accounts: 'cuenta(s)',
  tc_simTitle: 'Simular una sincronización', tc_apiKey: 'Clave API', tc_noKeys: 'Todavía no tienes ninguna clave. Créala primero.', tc_createKey: 'Crear una clave →',
  tc_notLinked: 'sin atar', tc_accNum: 'Número de cuenta a simular',
  tc_withPos: 'Incluir una posición abierta de ejemplo (EURUSD 0.50)',
  tc_simSync: 'Simular sync', tc_queueClose: 'Encolar "cerrar todo"', tc_queueBE: 'Encolar "SL a BE"',
  tc_simNote: 'Ojo: simular crea o actualiza esa cuenta en tu base de datos, igual que haría el EA de verdad.',
  tc_serverResp: 'Respuesta del servidor', tc_serverEmpty: 'Aquí verás lo que el servidor le contesta al EA: la configuración de Onyx Guardian y los comandos pendientes.',
  tc_serverHint1: 'Qué mirar:', tc_serverHint2: 'debe traer tus ajustes de Onyx Guardian (si es', tc_serverHint3: ', o Onyx Guardian está apagado o tu plan no lo incluye).', tc_serverHint4: 'debe traer lo que hayas encolado.',

  // Guía de errores (Diagnóstico)
  dg1t: 'La IA responde con un mensaje fijo (modo buscador)', dg1d: 'Falta ANTHROPIC_API_KEY, no hiciste Redeploy en Vercel, o no hay saldo en Anthropic.',
  dg2t: 'El EA muestra HTTP 404', dg2d: 'ServidorUrl con la ruta duplicada. Deja solo el dominio base: https://www.onyxtradinglive.com',
  dg3t: 'Telegram: 308 Permanent Redirect', dg3d: 'El webhook apunta al dominio sin www. Vuelve a configurar con https://www.onyxtradinglive.com',
  dg4t: 'No llegan los correos de soporte', dg4d: 'El dominio no está verificado en Resend, o falta RESEND_API_KEY. Añade los DNS y pulsa Verify.',
  dg5t: 'El EA dice "Sin señal"', dg5d: 'MetaTrader cerrado, AlgoTrading apagado, o falta permitir la URL en Herramientas → Opciones → WebRequest.',
  dg6t: 'Una página da "Application error"', dg6d: 'Casi siempre falta correr un SQL nuevo. Revisa arriba "Base de datos".',
};

type Dict = typeof ES;

const EN: Dict = {
  brand: 'Onyx Admin',
  g_op: 'Operations', g_prod: 'Product', g_growth: 'Growth', g_sys: 'System',
  nav_resumen: 'Overview', nav_usuarios: 'Users', nav_soporte: 'Support', nav_equipo: 'Team',
  nav_planes: 'Plans', nav_modulos: 'Modules', nav_firms: 'Prop firms',
  nav_embajadores: 'Ambassadors', nav_retencion: 'Retention',
  nav_kb: 'AI Base', nav_diag: 'Diagnostics', nav_backups: 'Backups', nav_audit: 'Audit', nav_pruebas: 'Tests', nav_ajustes: 'Settings',
  avail_on: 'Available', avail_off: 'Away',
  h_backups_t: 'Backups', h_backups_s: 'Protect trader data: export now or check the automatic backup.',
  h_audit_t: 'Audit', h_audit_s: 'Speed, quality and buttons — tested automatically on every deploy.',

  h_resumen_t: 'Overview', h_resumen_s: 'Your business pulse and what needs attention.',
  h_usuarios_t: 'Users', h_usuarios_registered: 'registered · search and manage.',
  h_soporte_t: 'Support', h_soporte_s: 'Shared queue — take, reply, invite a teammate.',
  h_equipo_t: 'Team and permissions', h_equipo_s: 'Add members, assign a role and fine-tune permissions by area.',
  h_equipo_s_ro: 'Only someone who manages the team can change roles.',
  h_planes_t: 'Plans', h_planes_s: 'Prices, features and real capabilities of each plan.',
  h_modulos_t: 'Modules', h_modulos_s: 'Live status of the system capabilities.',
  h_firms_t: 'Prop firms', h_firms_s: 'Templates the trader sees when setting limits. Fix here and everyone gets it.',
  h_embajadores_t: 'Ambassadors', h_embajadores_s: 'Referral program, commissions and payouts.',
  h_retencion_t: 'Retention', h_retencion_s: 'Save those trying to leave and measure why.',
  h_kb_t: 'AI knowledge base', h_kb_s: 'What you write here is used by Onyx AI to answer, alongside the Guide.',
  h_diag_t: 'Diagnostics', h_diag_s: 'System health and what still needs setup.',
  h_pruebas_t: 'Test console', h_pruebas_s: 'Simulate what the EA sends, without opening MetaTrader: key, limits and Onyx Guardian config.',
  h_ajustes_t: 'Settings', h_ajustes_s: 'Your role, admins and how access is organized.',

  r_mrr: 'Estimated MRR', r_paying: 'paying', r_conversion: 'conversion',
  r_users: 'Users', r_mtAccounts: 'MT accounts', r_trades: 'trades',
  r_team: 'Team', r_availableNow: 'available now', r_availableNow1: 'available now',
  r_banned: 'Banned',
  r_needs: 'Needs your attention', r_allGood: 'All clear', r_noPending: ' — nothing pending for now.',
  r_sqlMissing: 'SQL migration(s) not run', r_seeDiag: 'View Diagnostics',
  r_ticketsOpen: 'open support ticket(s)', r_openQueue: 'Open queue',
  r_svcConfig: 'service(s) to configure', r_review: 'Review',
  r_bannedUsers: 'banned user(s)', r_seeUsers: 'View users',

  u_search: 'Search by email…', u_admin: 'admin',
  u_active: 'active', u_banned: 'banned',
  u_unban: 'Unban', u_makeAdmin: 'Make admin', u_removeAdmin: 'Remove admin',

  t_you: ' (you)', t_lastActivity: 'Last activity: ', t_noActivity: 'No activity',
  t_perms: 'Permissions', t_close: 'Close', t_remove: 'Remove',
  t_permsByArea: 'Permissions by area', t_permsHint: '· the role sets defaults; fine-tune them here',
  t_invite: 'Invite member (must be registered in the app)',
  t_invitePh: 'email@example.com', t_inviteBtn: '+ Invite',
  t_activity: 'Activity log', t_member: 'Member:', t_all: 'All',
  t_noActivityTopic: 'No activity in this topic.',
  lvl_none: 'No access', lvl_view: 'View', lvl_manage: 'Manage',
  role_owner: 'Owner', role_admin: 'Admin', role_support: 'Support', role_marketing: 'Marketing', role_custom: 'Custom',
  lt_all: 'All', lt_equipo: 'Team', lt_soporte: 'Support', lt_baseia: 'AI Base', lt_usuarios: 'Users', lt_planes: 'Plans',

  s_open: 'Open', s_inprogress: 'In progress', s_resolved: 'Resolved', s_all: 'All',
  s_search: 'Search by email or subject…', s_empty: 'No conversations in this view.',
  s_pickOne: 'Pick a conversation on the left to see it here.',
  s_unassigned: 'unassigned', s_assignedTo: 'assigned to ',
  s_visitor: 'Visitor', s_inConvo: 'In the conversation: ',
  s_reply: 'Reply', s_note: 'Internal note', s_notePh: 'Note only the team can see…',
  s_replyPh: 'Reply for the trader (sent by email)…',
  s_sendReply: 'Send reply', s_saveNote: 'Save note', s_aiDraft: 'AI draft',
  s_take: 'Take', s_resolve: 'Resolve', s_reopen: 'Reopen',
  s_invitePh: 'Invite teammate (their team email)', s_inviteBtn: 'Invite',
  st_open: 'Open', st_inprogress: 'In progress', st_resolved: 'Resolved',
  sender_trader: 'Trader', sender_note: '🔒 Internal note', sender_support: 'Support',
  ch_ticket: 'Ticket', ch_chat: 'Chat', ch_lead: 'Lead', ch_email: 'Email',
  cat_general: 'General', cat_conexion: 'Connection', cat_instalacion: 'Install', cat_guardian: 'Onyx Guardian', cat_facturacion: 'Billing',

  d_refresh: '↻ Refresh', d_loading: 'Loading diagnostics…',
  d_quickTests: '⚡ Quick tests', d_testAI: '🤖 Test AI', d_testEmail: '📧 Send test email', d_testTG: '✈️ Test Telegram',
  d_db: '🗄️ Database (did you run the SQL?)', d_applied: '✓ applied', d_missing: '✗ not run',
  d_missingMsg: 'You still need to run in Supabase → SQL Editor: ',
  d_recentErrors: '🚨 Recent errors', d_noErrors: 'No errors logged. 🎉',
  d_commonErrors: '📖 Common errors explained',

  a_yourRole: 'Your role', a_rolesTitle: 'How roles work',
  a_rolesBody: 'The Owner controls plans, users and team. Admins manage users and plans. Support only views and helps.',
  a_rolesEnv: 'Emails in ADMIN_EMAILS on Vercel always come in as Owner. You can add more admins from the Team tab.',

  mo_guardian_desc: 'EA risk management on MT4 and MT5: break even, trailing, trading plan, limits and news.',
  mo_guardian_accounts: 'accounts with Guardian', mo_guardian_live: 'reporting now', mo_guardian_blocks: 'blocks executed',
  mo_connected: 'Connected', mo_liveNow: 'Online now', mo_withGuardian: 'With Guardian', mo_blocks: 'Blocks',
  mo_tg_desc: 'Guardian alerts, funding limits, EA down and daily summary. /status command included.',
  mo_tg_linked: 'linked users', mo_active: 'Active', mo_notoken: 'No token',
  mo_tg_connected: 'Connected', mo_tg_sent7d: 'Sent (7 d)', mo_tg_status: '/status used', mo_tg_failed: 'Failed',
  mo_rep_sent: 'Sent', mo_rep_eligible: 'Eligible', mo_rep_next: 'Next',
  mo_needLog: 'Some metrics need the telegram_log table (run the SQL). They start at 0 and grow for real.',
  mo_liveBadge: 'Live', d_liveBadge: 'Live',
  mo_weekly_t: 'Weekly report', mo_weekly_desc: 'Every Sunday, a report of the week by Telegram: result, win rate, best pair and discipline.',

  pl_count: 'Plans', pl_new: '+ New plan', pl_month: '$ / month', pl_year: '$ / year',
  pl_es: '🇪🇸 SPANISH', pl_en: '🇬🇧 ENGLISH', pl_caps: '🎛️ CAPABILITIES (real control)', pl_stripe: '💳 STRIPE',
  pl_id: 'id (pro)', pl_name: 'Name', pl_desc: 'Short description', pl_badge: 'Badge (e.g. Most popular)', pl_features: 'Features (one per line)',
  pl_nameEn: 'Name', pl_descEn: 'Short description', pl_badgeEn: 'Badge (e.g. Most popular)', pl_featuresEn: 'Features (one per line)',
  pl_mtAccounts: 'MT accounts', pl_historyDays: 'History days', pl_unlimited: '(0 = unlimited)',
  pl_priceIdM: 'Monthly Price ID (price_...)', pl_priceIdY: 'Yearly Price ID (price_...)',
  pl_activeChk: 'Active (visible on landing and /pricing)',
  pl_create: 'Create plan', pl_save: 'Save', pl_cancel: 'Cancel', pl_delete: 'Delete', pl_confirmDel: 'Delete the plan',
  cap_journal: 'Journal with photos and notes', cap_compare: 'Compare accounts', cap_funding: 'Funding rules and payouts', cap_costs: 'Costs (commission and swap)', cap_export: 'Export CSV', cap_reports: 'Automatic reports', cap_telegram: 'Telegram alerts', cap_manager: 'Onyx Guardian: break even, trailing, plan and limits', cap_manager_advanced: 'Advanced Guardian: partial TPs', cap_manager_news: 'Guardian: news blocking',

  fi_intro: 'They are the starting point the trader sees when setting their limits. They are not any firm’s official rule: if one changes its rules, fix it here and every user sees it instantly. The two most-confused fields are calculation base and reset hour, so they are always visible.',
  fi_default: 'Factory templates are currently in use.',
  fi_new: 'New template', fi_id: 'Identifier', fi_name: 'Display name', fi_daily: 'Daily loss %', fi_total: 'Total loss %',
  fi_base: 'Calculation base', fi_base1: 'Balance at day start', fi_base2: 'Equity at day start', fi_base3: 'Initial balance',
  fi_reset: 'Reset hour', fi_noteEs: 'Note (ES)', fi_noteEn: 'Note (EN)', fi_remove: 'Remove',
  fi_confused: '⚠ The 2 most-confused fields', fi_daily_s: 'daily', fi_total_s: 'total',
  fi_add: '+ Add template', fi_save: 'Save', fi_resetBtn: 'Reset to factory', fi_saved: 'Saved',
  fi_badPre: 'There are', fi_bad: 'template(s) without identifier or name. Complete them to save.',
  fi_confirmReset: 'Reset to factory templates?',

  am_ambassadors: 'Ambassadors', am_requests: 'Requests', am_brought: 'Subscribers brought', am_toPay: 'To pay',
  am_payouts: 'Payout requests', am_markPaid: 'Mark paid', am_reject: 'Reject',
  am_confirmPaid: 'Confirm you already paid', am_rejectReason: 'Rejection reason:',
  am_rules: '⚙️ Program rules', am_baseRate: 'Base %', am_goldRate: 'Gold tier %', am_goldActive: 'Active for Gold', am_holdDays: 'Hold days',
  am_minPayout: 'Min payout $', am_couponPct: 'Coupon %', am_couponMonths: 'Coupon months',
  am_open: 'Program open (accepts requests and generates commissions)', am_saveRules: 'Save rules',
  am_couponNote: 'The coupon % applies when approving new ambassadors. Existing coupons don’t change.',
  am_list: 'Ambassadors', am_empty: 'No requests yet.',
  am_code: 'code', am_followers: 'followers',
  am_approve: 'Approve', am_pause: 'Pause', am_reactivate: 'Reactivate',
  am_clicks: 'Clicks', am_signups: 'Signups', am_active: 'Active', am_conversion: 'Conversion',
  am_pending: 'Pending', am_available: 'Available', am_paid: 'Paid',
  am_ownRate: 'Own commission:', am_ownRateHint: '% (empty = by tier)',
  am_gold: 'Gold', am_silver: 'Silver',
  st_pending: 'Pending', st_approved: 'Approved', st_rejected: 'Rejected', st_paused: 'Paused',
  am_promoFail: 'Approved, but the Stripe coupon couldn’t be created. Check your Stripe key.',

  re_attempts: 'Cancel attempts', re_saved: 'Saved', re_lost: 'Lost', re_rate: 'Save rate',
  re_whyLeave: 'Why they want to leave', re_noneYet: 'Nobody has tried to cancel yet.',
  re_offers: '🛟 Rescue offers', re_discPct: 'Discount %', re_discMonths: 'Discount months', re_pauseMonths: 'Pause months',
  re_allowDown: 'Offer to downgrade to a cheaper plan', re_flowOn: 'Retention flow active', re_saveOffers: 'Save offers',
  re_extra: '➕ Extra MT accounts', re_extraDesc: 'Create a monthly recurring price per unit in Stripe and paste its Price ID here. Without it, the add-on is hidden.',
  re_extraPrice: 'Price per account / month ($)', re_extraId: 'Stripe Price ID', re_addonOn: 'Add-on active', re_saveAddon: 'Save add-on',
  re_recent: 'Recent attempts', re_recentEmpty: 'Nothing yet.',
  reason_price: 'Too expensive', reason_unused: 'Wasn’t using it', reason_missing: 'Missing something', reason_stopped: 'Stopped trading', reason_other: 'Other',
  out_discount: 'Saved · discount', out_pause: 'Saved · pause', out_downgrade: 'Saved · downgraded', out_canceled: 'Canceled', out_pending: 'Unresolved',

  kb_new: '+ New article', kb_intro: 'What you write here is used by the AI to answer, alongside the Guide. Ideal for prices, promos, policies or FAQs that change.',
  kb_title: 'Title', kb_titlePh: 'e.g. Do you offer a free trial?', kb_body: 'Content (the answer)',
  kb_tags: 'Keywords (comma-separated, help find it)', kb_tagsPh: 'trial, free, demo',
  kb_published: 'Published (the AI uses it)', kb_save: 'Save', kb_cancel: 'Cancel',
  kb_emptyEdit: 'Add a title and content.', kb_confirmDel: 'Delete this article from the AI base?',
  kb_empty: 'No articles yet. Create the first so the AI knows more.',
  kb_hidden: 'hidden', kb_hide: 'Hide', kb_publish: 'Publish', kb_edit: 'Edit', kb_delete: 'Delete',

  tc_myPlan: 'My test plan', tc_myPlanDesc: 'Switch plans to test the locks and Onyx Guardian. It’s your own account',
  tc_currentPlan: 'Current plan', tc_of: 'of', tc_unlimited: 'unlimited', tc_accounts: 'account(s)',
  tc_simTitle: 'Simulate a sync', tc_apiKey: 'API key', tc_noKeys: 'You don’t have any key yet. Create it first.', tc_createKey: 'Create a key →',
  tc_notLinked: 'unlinked', tc_accNum: 'Account number to simulate',
  tc_withPos: 'Include a sample open position (EURUSD 0.50)',
  tc_simSync: 'Simulate sync', tc_queueClose: 'Queue "close all"', tc_queueBE: 'Queue "SL to BE"',
  tc_simNote: 'Note: simulating creates or updates that account in your database, just like the real EA would.',
  tc_serverResp: 'Server response', tc_serverEmpty: 'Here you’ll see what the server replies to the EA: the Onyx Guardian config and pending commands.',
  tc_serverHint1: 'What to look at:', tc_serverHint2: 'should carry your Onyx Guardian settings (if', tc_serverHint3: ', either Onyx Guardian is off or your plan doesn’t include it).', tc_serverHint4: 'should carry what you queued.',

  dg1t: 'The AI replies with a fixed message (search mode)', dg1d: 'ANTHROPIC_API_KEY is missing, you didn’t Redeploy on Vercel, or there’s no Anthropic balance.',
  dg2t: 'The EA shows HTTP 404', dg2d: 'ServerUrl has the path duplicated. Leave only the base domain: https://www.onyxtradinglive.com',
  dg3t: 'Telegram: 308 Permanent Redirect', dg3d: 'The webhook points to the domain without www. Set it again with https://www.onyxtradinglive.com',
  dg4t: 'Support emails don’t arrive', dg4d: 'The domain isn’t verified in Resend, or RESEND_API_KEY is missing. Add the DNS and click Verify.',
  dg5t: 'The EA says "No signal"', dg5d: 'MetaTrader closed, AlgoTrading off, or the URL isn’t allowed in Tools → Options → WebRequest.',
  dg6t: 'A page shows "Application error"', dg6d: 'Almost always a new SQL is missing. Check "Database" above.',
};

const AT: Record<string, Dict> = { es: ES, en: EN };

export function useT(): Dict {
  const { lang } = useLang();
  return AT[lang] || ES;
}
