import type { BotSpec } from '@/lib/botSpec';

// Generador del EA MT5 (Fase 2) con UNIDADES por campo ($, %, pips, RR/ATR según
// aplique). El EA convierte cada unidad a distancia de precio o dinero en runtime.
// Compilar en MetaEditor y PROBAR EN DEMO. Responsabilidad del trader.

const b = (v: boolean) => (v ? 'true' : 'false');
const TF: Record<string, string> = {
  M1: 'PERIOD_M1', M2: 'PERIOD_M2', M3: 'PERIOD_M3', M4: 'PERIOD_M4', M5: 'PERIOD_M5', M6: 'PERIOD_M6',
  M10: 'PERIOD_M10', M12: 'PERIOD_M12', M15: 'PERIOD_M15', M20: 'PERIOD_M20', M30: 'PERIOD_M30',
  H1: 'PERIOD_H1', H2: 'PERIOD_H2', H3: 'PERIOD_H3', H4: 'PERIOD_H4', H6: 'PERIOD_H6', H8: 'PERIOD_H8', H12: 'PERIOD_H12',
  D1: 'PERIOD_D1', W1: 'PERIOD_W1', MN1: 'PERIOD_MN1',
};
const tf = (x: string) => TF[x] || 'PERIOD_M5';
const q = (s: string) => '"' + String(s).replace(/"/g, "'") + '"';
const cRisk = (u: string) => (u === 'money' ? 1 : 0);
// Código unificado de unidad de salida: pips=0, R=1, %=2, $=3, ATR=4.
const cU = (u: string) => ({ pips: 0, rr: 1, pct: 2, money: 3, atr: 4 } as any)[u] ?? 0;
const cSL = cU, cTP = cU, cRun = cU, cTrail = cU;

export function renderMT5(spec: BotSpec, meta?: { userId?: string; buildId?: string; site?: string }): string {
  const s = spec;
  const en = s.botLang === 'en';
  const T = (a: string, b: string) => (en ? b : a); // textos visibles al trader, en su idioma
  // Datos para el candado de activación: URL de Onyx + huella (creador + build) que
  // permite rastrear cualquier archivo filtrado. Se incrustan como constantes del EA.
  const site = String(meta?.site || 'https://www.onyxtradinglive.com').replace(/\/$/, '');
  const creator = String(meta?.userId || '').replace(/[^\w-]/g, '');
  const buildId = String(meta?.buildId || '').replace(/[^\w-]/g, '');
  const trig = { breakout_swing: 0, ma_cross: 1, rsi: 2, donchian: 3, time: 4 }[s.entryTrigger] ?? 1;
  const nImpact = ({ high: 0, med: 1, all: 2 } as any)[s.newsImpact] ?? 0;
  return `//+------------------------------------------------------------------+
//|  ${s.name}  ·  ${T('generado por Onyx Bot Builder', 'generated by Onyx Bot Builder')}
//|  ${T('Unidades por campo ($, %, pips, RR/ATR). Compila en MetaEditor.', 'Per-field units ($, %, pips, RR/ATR). Compile in MetaEditor.')}
//|  ${T('PRUEBA EN DEMO antes de real. Responsabilidad del trader.', 'TEST ON DEMO before going live. The trader is responsible.')}
//+------------------------------------------------------------------+
#property copyright ${q(s.name)}
#property version   "2.00"
#property strict
#include <Trade/Trade.mqh>
#include <Trade/PositionInfo.mqh>
CTrade        trade;
CPositionInfo pos;

enum ENUM_ACCT_MODE { MODE_FASE1=0, MODE_FASE2=1, MODE_REAL=2 };
enum ENUM_DD_TYPE   { DD_TRAIL=0, DD_STATIC=1, DD_TRAIL_BE=2 };
enum ENUM_ENTRY     { ENT_SWING=0, ENT_MA=1, ENT_RSI=2, ENT_DONCH=3, ENT_TIME=4 };
enum ENUM_U_RISK    { UR_PCT=0, UR_MONEY=1 };            // %  |  $
// Mismo set de unidades para SL, TP1, runner y trailing.
enum ENUM_U         { U_PIPS=0, U_RR=1, U_PCT=2, U_MONEY=3, U_ATR=4 }; // pips | R | %precio | $ | ATR

//====================== INPUTS ======================
input string  InpComment      = ${q(s.name)};
input string  InpSymbol       = ${q(s.symbol)};
input long    InpMagic        = ${s.magic};
input string  InpApiKey       = "";   // ${T('Tu clave Onyx (Conectar cuenta). Requerida en cuentas reales.', 'Your Onyx key (Connect account). Required on live accounts.')}
input ENUM_TIMEFRAMES InpTF    = ${tf(s.tf)};

input ENUM_ENTRY InpEntry     = ${trig};
input int     InpMAfast       = 12;
input int     InpMAslow       = 50;
input int     InpRSIperiod    = 14;
input double  InpRSIos        = 30;
input double  InpRSIob        = 70;
input int     InpDonchN       = 20;
input int     InpMicroSwing   = ${s.microSwing};
input int     InpEntryHour    = 9;

input int     InpTrendMode    = ${s.trendMode};
input ENUM_TIMEFRAMES InpTrendTF = ${tf(s.trendTF)};
input int     InpTrendMA      = 50;
input int     InpTrendSwing   = 6;
input int     InpTrendDonchN  = 20;
input bool    InpAllowLongs   = ${b(s.allowLongs)};
input bool    InpAllowShorts  = ${b(s.allowShorts)};
input int     InpSignalFromH  = ${s.signalFromH};
input int     InpSignalFromM  = ${s.signalFromM};
input int     InpSignalToH    = ${s.signalToH};
input int     InpSignalToM    = ${s.signalToM};
input int     InpMaxTradesPerDay = ${s.maxTradesPerDay};

// RIESGO por operacion (elige unidad)
input ENUM_U_RISK InpRiskUnit  = ${cRisk(s.riskUnit)};  // %  |  $
input double  InpRiskValue    = ${s.riskVal};
input double  InpMaxLots       = ${s.maxLots};
input int     InpATRPeriod     = 14;
// STOP LOSS (elige unidad: pips | R | %precio | $ | ATR)
input ENUM_U  InpSLUnit       = ${cSL(s.slUnit)};
input double  InpSLValue      = ${s.slVal};
// TP1 parcial (elige unidad: pips | R | %precio | $ | ATR)
input ENUM_U  InpTP1Unit      = ${cTP(s.tp1Unit)};
input double  InpTP1Value     = ${s.tp1Val};
input double  InpPartialPct   = ${s.partialPct};
// RUNNER / TP final (elige unidad: pips | R | %precio | $ | ATR)
input ENUM_U  InpRunnerUnit   = ${cRun(s.runnerUnit)};
input double  InpRunnerValue  = ${s.runnerVal};
// TRAILING (elige unidad: pips | R | %precio | $ | ATR)
input bool    InpUseTrail     = ${b(s.useTrail)};
input ENUM_U  InpTrailUnit    = ${cTrail(s.trailUnit)};
input double  InpTrailValue   = ${s.trailVal};
input double  InpBEOffsetR    = ${s.beOffsetR};
input int     InpTimeStopBars = ${s.timeStopBars};

// CAP de perdida diaria (elige unidad)
input ENUM_U_RISK InpDailyLossUnit = ${cRisk(s.dailyLossUnit)}; // %  |  $
input double  InpDailyLossValue = ${s.dailyLossVal};
// OBJETIVO de ganancia diaria (elige unidad). 0 = off
input ENUM_U_RISK InpDailyProfitUnit = ${cRisk(s.dailyProfitUnit)};
input double  InpDailyProfitValue = ${s.dailyProfitVal};

input string  InpFirmName     = ${q(s.firmName)};
input ENUM_DD_TYPE InpDDType   = ${s.ddType};
input double  InpFirmTotalLimitPct = ${s.firmTotalLimitPct};
input double  InpAcctSoftStopPct = ${s.acctSoftStopPct};
input double  InpAcctDailyStopPct= ${s.acctDailyStopPct};
input double  InpAcctMaxDDPct    = ${s.acctMaxDDPct};

input ENUM_ACCT_MODE InpAccountMode = ${s.accountMode};
input double  InpInitBalance  = ${s.initBalance};
input double  InpTargetP1     = ${s.targetP1};
input double  InpTargetP2     = ${s.targetP2};
input bool    InpHaltAtTarget = true;

input bool    InpUseDayClose  = ${b(s.useDayClose)};
input int     InpForceCloseHourNY = ${s.forceCloseHourNY};
input int     InpForceCloseMinNY  = ${s.forceCloseMinNY};
input bool    InpNoWeekend    = ${b(s.noWeekend)};
input int     InpFridayHour   = 21;
input int     InpServerGmt    = ${s.serverGmt};   // GMT del servidor del broker (para noticias)
// NOTICIAS (Forex Factory). Requiere permitir la URL en MetaTrader:
// Herramientas > Opciones > Asesores expertos > Permitir WebRequest para:
//   https://nfs.faireconomy.media
input bool    InpUseNews      = ${b(s.useNewsFilter)};
input string  InpNewsCur      = ${q(s.newsCurrencies)};   // monedas separadas por coma, ej: USD,EUR
input int     InpNewsImpact   = ${nImpact};               // 0=solo alto  1=alto+medio  2=todos
input int     InpNewsBefore   = ${s.newsBefore};          // minutos antes de la noticia
input int     InpNewsAfter    = ${s.newsAfter};           // minutos despues
input bool    InpShowPanel    = true;
input int     InpPanelX       = 12;
input int     InpPanelY       = 20;

//====================== GLOBALES ======================
string S=""; int gDigits=0; double point=0, minStop=0;
int atrH=INVALID_HANDLE, maF=INVALID_HANDLE, maS=INVALID_HANDLE, rsiH=INVALID_HANDLE, trendH=INVALID_HANDLE;
ulong tk=0; long ptype=-1; double entryPx=0, riskPx=0, gInitVol=0, gTP1dist=0; bool gTP1done=false; datetime openBar=0;
datetime lastBar=0; int gTradesToday=0, curDayId=-1; double dayStartEq=0, gInitBal=0, gPeakEq=0;
bool dayLocked=false, gTargetHit=false, gDayGoal=false; string PFX="OBX_"; string noReason="${T('Iniciando', 'Starting')}";
int stTrades=0, stWins=0; double stNet=0, stWR=0;
datetime nwT[]; int nwImp[]; string nwCur[]; datetime nwLast=0; bool nwFail=false; bool gInNews=false;

//====================== ACTIVACION ONYX ======================
// Huella del EA (creador + build) e identidad del sitio. La operación en cuentas
// REALES requiere una clave Onyx activa; en DEMO se permite probar sin clave.
#define ONYX_SITE    "${site}"
#define ONYX_CREATOR "${creator}"
#define ONYX_BUILD   "${buildId}"
bool     gAuth=false; datetime gAuthUntil=0, gAuthLastOk=0, gAuthLastTry=0;
string   gAuthMsg="${T('Verificando activacion...', 'Checking activation...')}";
bool IsDemo(){ return (AccountInfoInteger(ACCOUNT_TRADE_MODE)==ACCOUNT_TRADE_MODE_DEMO); }
// Consulta a Onyx si esta cuenta+clave puede operar este robot. Tolerante a caídas
// de red: mantiene la última autorización válida hasta 72h (no atrapa al trader).
void Activate(){
   gAuthLastTry=TimeCurrent();
   if(IsDemo()){ gAuth=true; gAuthUntil=TimeCurrent()+86400; gAuthMsg="${T('Demo (libre)', 'Demo (free)')}"; return; }
   if(StringLen(InpApiKey)<8){ gAuth=false; gAuthMsg="${T('Pega tu clave Onyx (real)', 'Paste your Onyx key (live)')}"; return; }
   string q=CharToString((uchar)34);
   string body="{"+q+"key"+q+":"+q+InpApiKey+q+","+q+"account"+q+":"+(string)AccountInfoInteger(ACCOUNT_LOGIN)+","
      +q+"magic"+q+":"+(string)InpMagic+","+q+"build"+q+":"+q+ONYX_BUILD+q+","+q+"creator"+q+":"+q+ONYX_CREATOR+q+"}";
   char post[], res[]; string headers="Content-Type: application/json\\r\\n";
   int blen=StringToCharArray(body,post,0,WHOLE_ARRAY,CP_UTF8)-1; if(blen<0) blen=0; ArrayResize(post,blen);
   string resH; ResetLastError();
   int r=WebRequest("POST",ONYX_SITE+"/api/v1/activate",headers,5000,post,res,resH);
   if(r!=200){
      // Sin conexión: conserva la última autorización buena dentro del periodo de gracia.
      if(gAuthLastOk>0 && TimeCurrent()-gAuthLastOk<72*3600){ gAuthMsg="${T('Sin conexion (en gracia)', 'Offline (grace)')}"; return; }
      gAuth=false; gAuthMsg="${T('Permite la URL de Onyx en Opciones > Asesores expertos', 'Allow the Onyx URL in Options > Expert Advisors')}"; return; }
   string j=CharArrayToString(res,0,WHOLE_ARRAY,CP_UTF8);
   bool allowed=(StringFind(j,q+"allowed"+q+":true")>=0);
   if(allowed){ gAuth=true; gAuthLastOk=TimeCurrent(); gAuthUntil=TimeCurrent()+24*3600; gAuthMsg="${T('Activo', 'Active')}"; }
   else { gAuth=false; gAuthMsg="${T('Clave/plan no activo para esta cuenta', 'Key/plan not active for this account')}"; }
}

datetime SrvNow(){ return TimeCurrent(); }
int DayId(){ MqlDateTime d; TimeToStruct(SrvNow(),d); return d.year*1000+d.day_of_year; }
int RefMin(){ MqlDateTime d; TimeToStruct(SrvNow(),d); return d.hour*60+d.min; }
int RefDow(){ MqlDateTime d; TimeToStruct(SrvNow(),d); return d.day_of_week; }
bool InWindow(){ int m=RefMin(), f=InpSignalFromH*60+InpSignalFromM, t=InpSignalToH*60+InpSignalToM; return (f<=t)?(m>=f&&m<=t):(m>=f||m<=t); }
bool DayOperable(){ int w=RefDow(); return (w>=1&&w<=5); }
bool ForceClose(){ if(!InpUseDayClose) return false; return RefMin()>=InpForceCloseHourNY*60+InpForceCloseMinNY; }
bool FridayCut(){ if(!InpNoWeekend) return false; if(RefDow()!=5) return false; return RefMin()>=InpFridayHour*60; }
bool NewBar(){ datetime t[]; if(CopyTime(S,InpTF,0,1,t)<=0) return false; if(t[0]!=lastBar){ lastBar=t[0]; return true; } return false; }
double Atr(){ double a[]; if(atrH!=INVALID_HANDLE && CopyBuffer(atrH,0,1,1,a)>0) return a[0]; return 0; }
double PipSize(){ return point*((gDigits==3||gDigits==5)?10.0:1.0); }
double TickVal(){ return SymbolInfoDouble(S,SYMBOL_TRADE_TICK_VALUE); }
double TickSz(){ return SymbolInfoDouble(S,SYMBOL_TRADE_TICK_SIZE); }

// Deja solo A-Z0-9 en mayusculas (para comparar entre brokers).
string NormSym(string x){ StringToUpper(x); string o=""; for(int i=0;i<StringLen(x);i++){ ushort c=StringGetCharacter(x,i); if((c>='A'&&c<='Z')||(c>='0'&&c<='9')) o+=ShortToString(c); } return o; }
// Lista de alias del simbolo pedido (nombres equivalentes en distintos brokers).
void Aliases(string want,string &out[]){ string w=NormSym(want); ArrayResize(out,1); out[0]=w;
   string groups[]={ "XAUUSD,GOLD,GOLDUSD", "XAGUSD,SILVER,SILVERUSD", "US30,DJ30,WS30,DOW,DJIA,US30USD,USA30", "NAS100,USTEC,NDX,US100,NAS,NASDAQ,USATECH", "SPX500,US500,SP500,SPX,USA500", "GER40,DE40,DAX,DAX40,GER30", "UK100,FTSE100,FTSE", "US2000,RUSSELL,RUT", "USOIL,WTI,CRUDE,OIL,USOUSD,XTIUSD", "UKOIL,BRENT,XBRUSD", "BTCUSD,BITCOIN,BTC", "ETHUSD,ETHEREUM,ETH", "JP225,NIKKEI,JPN225,JP225USD", "USDX,DXY,USDOLLAR" };
   for(int g=0;g<ArraySize(groups);g++){ string parts[]; int k=StringSplit(groups[g],',',parts); bool in=false; for(int p=0;p<k;p++) if(NormSym(parts[p])==w){ in=true; break; }
      if(in) for(int p=0;p<k;p++){ string a=NormSym(parts[p]); int m=ArraySize(out); ArrayResize(out,m+1); out[m]=a; } } }
// Resuelve el simbolo aunque el broker use sufijos (.m, m, .raw, +, etc.) o nombres alternos.
string ResolveSymbol(string want){ if(want==""||want==NULL) return _Symbol; if(SymbolSelect(want,true)) return want;
   string al[]; Aliases(want,al); int tot=SymbolsTotal(false);
   for(int i=0;i<tot;i++){ string nm=SymbolName(i,false); string x=NormSym(nm); for(int a=0;a<ArraySize(al);a++) if(x==al[a] && SymbolSelect(nm,true)) return nm; }
   for(int i=0;i<tot;i++){ string nm=SymbolName(i,false); string x=NormSym(nm); for(int a=0;a<ArraySize(al);a++) if(StringLen(al[a])>=3 && StringFind(x,al[a])==0 && SymbolSelect(nm,true)) return nm; }
   for(int i=0;i<tot;i++){ string nm=SymbolName(i,false); string x=NormSym(nm); for(int a=0;a<ArraySize(al);a++) if(StringLen(al[a])>=4 && StringFind(x,al[a])>=0 && SymbolSelect(nm,true)) return nm; }
   return _Symbol; }

//====================== CONVERSION DE UNIDADES ======================
// Convierte (valor+unidad) a distancia de precio. base = distancia de referencia para R
// (el stop); lots = tamano (para convertir $ a distancia). Mismo motor para SL/TP/trailing.
double UnitDist(int unit,double val,double base,double lots,double atr){
   if(val<=0) return 0;
   if(unit==U_PIPS) return val*PipSize();
   if(unit==U_ATR)  return val*atr;
   if(unit==U_PCT){ double px=SymbolInfoDouble(S,SYMBOL_BID); return px*val/100.0; }
   if(unit==U_RR)   return val*base;                                  // R = multiplo del riesgo
   double ts=TickSz(), tv=TickVal(); if(ts<=0||tv<=0||lots<=0) return (base>0?val*base:val*atr); return val*ts/(lots*tv); } // $
// Distancia del STOP. Para R no hay base aun -> usa el ATR como base de referencia.
double SLdist(double atr){ double d=UnitDist(InpSLUnit,InpSLValue,atr,0,atr); if(d<=0) d=(atr>0?atr:PipSize()*10); return d; }
// Distancia de un TP: base = distancia del stop (para R), lots (para $).
double TPdist(double slDist,double lots,int unit,double val,double atr){ double d=UnitDist(unit,val,slDist,lots,atr); if(d<=0) d=slDist*2.0; return d; }
double TrailDist(double atr){ double d=UnitDist(InpTrailUnit,InpTrailValue,riskPx,gInitVol,atr); if(d<=0) d=atr; return d; }
// Riesgo en dinero por operacion. Si el SL esta en $, ese $ define el riesgo.
double RiskMoney(){ double eq=AccountInfoDouble(ACCOUNT_EQUITY); if(InpSLUnit==U_MONEY) return InpSLValue; if(InpRiskUnit==UR_MONEY) return InpRiskValue; return eq*InpRiskValue/100.0; }
double DailyCapMoney(){ if(InpDailyLossUnit==UR_MONEY) return InpDailyLossValue; return dayStartEq*InpDailyLossValue/100.0; }
double DailyTgtMoney(){ if(InpDailyProfitUnit==UR_MONEY) return InpDailyProfitValue; return dayStartEq*InpDailyProfitValue/100.0; }

//====================== SESGO ======================
int TrendDir(){
   if(InpTrendMode==0){ if(trendH==INVALID_HANDLE) return 0; double m[]; if(CopyBuffer(trendH,0,0,1,m)<1) return 0; double px=SymbolInfoDouble(S,SYMBOL_BID); return (px>m[0])?1:((px<m[0])?-1:0); }
   if(InpTrendMode==2){ int N=InpTrendDonchN; if(N<2)N=2; MqlRates r[]; ArraySetAsSeries(r,true); if(CopyRates(S,InpTrendTF,1,N,r)<N) return 0; double hh=-DBL_MAX,ll=DBL_MAX; for(int i=0;i<N;i++){ if(r[i].high>hh)hh=r[i].high; if(r[i].low<ll)ll=r[i].low; } double mid=(hh+ll)/2.0, px=SymbolInfoDouble(S,SYMBOL_BID); return (px>mid)?1:((px<mid)?-1:0); }
   int k=InpTrendSwing; if(k<1)k=1; MqlRates r[]; ArraySetAsSeries(r,true); int got=CopyRates(S,InpTrendTF,0,260,r); if(got<2*k+3) return 0;
   double sh[],sl[]; for(int i=k+1;i<=got-k-1;i++){ bool isH=true,isL=true;
      for(int j=1;j<=k;j++){ if(r[i].high<=r[i-j].high||r[i].high<=r[i+j].high) isH=false; if(r[i].low>=r[i-j].low||r[i].low>=r[i+j].low) isL=false; if(!isH&&!isL) break; }
      if(isH){ int n=ArraySize(sh); ArrayResize(sh,n+1); sh[n]=r[i].high; } if(isL){ int n=ArraySize(sl); ArrayResize(sl,n+1); sl[n]=r[i].low; } if(ArraySize(sh)>=2 && ArraySize(sl)>=2) break; }
   if(ArraySize(sh)<2||ArraySize(sl)<2) return 0; if(sh[0]>sh[1] && sl[0]>sl[1]) return 1; if(sh[0]<sh[1] && sl[0]<sl[1]) return -1; return 0; }

//====================== SEÑAL DE ENTRADA ======================
int EntrySignal(){
   if(InpEntry==ENT_MA){ if(maF==INVALID_HANDLE||maS==INVALID_HANDLE) return 0; double f[],sw[]; if(CopyBuffer(maF,0,1,2,f)<2||CopyBuffer(maS,0,1,2,sw)<2) return 0; bool up=(f[1]<=sw[1] && f[0]>sw[0]); bool dn=(f[1]>=sw[1] && f[0]<sw[0]); return up?1:(dn?-1:0); }
   if(InpEntry==ENT_RSI){ if(rsiH==INVALID_HANDLE) return 0; double v[]; if(CopyBuffer(rsiH,0,1,2,v)<2) return 0; bool up=(v[1]<=InpRSIos && v[0]>InpRSIos); bool dn=(v[1]>=InpRSIob && v[0]<InpRSIob); return up?1:(dn?-1:0); }
   if(InpEntry==ENT_DONCH){ int N=InpDonchN; if(N<2)N=2; MqlRates r[]; ArraySetAsSeries(r,true); if(CopyRates(S,InpTF,1,N+1,r)<N+1) return 0; double hh=-DBL_MAX,ll=DBL_MAX; for(int i=1;i<=N;i++){ if(r[i].high>hh)hh=r[i].high; if(r[i].low<ll)ll=r[i].low; } if(r[0].close>hh) return 1; if(r[0].close<ll) return -1; return 0; }
   if(InpEntry==ENT_TIME){ MqlDateTime d; TimeToStruct(SrvNow(),d); if(d.hour==InpEntryHour && d.min<5) return 1; return 0; }
   int k=InpMicroSwing; if(k<1)k=1; MqlRates r[]; ArraySetAsSeries(r,true); int got=CopyRates(S,InpTF,0,120,r); if(got<2*k+4) return 0;
   double hi=0,lo=0; for(int i=k+1;i<=got-k-1;i++){ bool isH=true; for(int j=1;j<=k;j++) if(r[i].high<=r[i-j].high||r[i].high<=r[i+j].high){ isH=false; break; } if(isH){ hi=r[i].high; break; } }
   for(int i=k+1;i<=got-k-1;i++){ bool isL=true; for(int j=1;j<=k;j++) if(r[i].low>=r[i-j].low||r[i].low>=r[i+j].low){ isL=false; break; } if(isL){ lo=r[i].low; break; } }
   if(hi>0 && r[1].close>hi) return 1; if(lo>0 && r[1].close<lo) return -1; return 0; }

//====================== RIESGO / EJECUCION ======================
double CalcLots(double slDist){ if(slDist<=0) return 0; double riskMoney=RiskMoney(); double ts=TickSz(), tv=TickVal(); if(ts<=0||tv<=0) return 0;
   double lots=riskMoney/((slDist/ts)*tv); double step=SymbolInfoDouble(S,SYMBOL_VOLUME_STEP), mn=SymbolInfoDouble(S,SYMBOL_VOLUME_MIN), mx=SymbolInfoDouble(S,SYMBOL_VOLUME_MAX);
   if(step>0) lots=MathFloor(lots/step)*step; if(lots<mn) lots=mn; if(lots>mx) lots=mx; if(lots>InpMaxLots) lots=InpMaxLots; return lots; }
double AdjVol(double v){ double step=SymbolInfoDouble(S,SYMBOL_VOLUME_STEP),mn=SymbolInfoDouble(S,SYMBOL_VOLUME_MIN); if(step>0) v=MathFloor(v/step)*step; if(v<mn) v=mn; return v; }
int CountMine(){ int n=0; for(int i=PositionsTotal()-1;i>=0;i--){ ulong t=PositionGetTicket(i); if(t==0)continue; if(pos.SelectByTicket(t)&&pos.Symbol()==S&&pos.Magic()==InpMagic) n++; } return n; }
void CloseMine(string why){ for(int i=PositionsTotal()-1;i>=0;i--){ ulong t=PositionGetTicket(i); if(t==0)continue; if(pos.SelectByTicket(t)&&pos.Symbol()==S&&pos.Magic()==InpMagic) trade.PositionClose(t); } }

void OpenTrade(int dir){ double atr=Atr(); if(atr<=0) return; double slDist=SLdist(atr); if(slDist<minStop) slDist=minStop; if(atr>0 && slDist<0.2*atr) slDist=0.2*atr;
   double ask=SymbolInfoDouble(S,SYMBOL_ASK), bid=SymbolInfoDouble(S,SYMBOL_BID);
   double lots=CalcLots(slDist); if(lots<=0) return;
   double runDist=TPdist(slDist,lots,InpRunnerUnit,InpRunnerValue,atr); if(runDist<slDist) runDist=slDist*2.0;
   double entry=(dir>0)?ask:bid; double sl=(dir>0)?entry-slDist:entry+slDist; double tp=(dir>0)?entry+runDist:entry-runDist;
   sl=NormalizeDouble(sl,gDigits); tp=NormalizeDouble(tp,gDigits);
   bool okk=(dir>0)?trade.Buy(lots,S,ask,sl,tp,InpComment):trade.Sell(lots,S,bid,sl,tp,InpComment);
   if(okk){ gTradesToday++; gTP1done=false; } }

void Manage(){ ulong found=0; for(int i=PositionsTotal()-1;i>=0;i--){ ulong t=PositionGetTicket(i); if(t==0)continue; if(pos.SelectByTicket(t)&&pos.Symbol()==S&&pos.Magic()==InpMagic){ found=t; break; } }
   if(found==0){ tk=0; gTP1done=false; return; } pos.SelectByTicket(found); double atr=Atr();
   if(found!=tk){ tk=found; entryPx=pos.PriceOpen(); ptype=pos.PositionType(); gInitVol=pos.Volume(); openBar=lastBar;
      double sl0=pos.StopLoss(); riskPx=(sl0>0)?MathAbs(entryPx-sl0):SLdist(atr); if(riskPx<=0) riskPx=(atr>0?atr:PipSize()*10);
      gTP1dist=TPdist(riskPx,gInitVol,InpTP1Unit,InpTP1Value,atr); if(gTP1dist<=0) gTP1dist=riskPx; gTP1done=false; }
   double bid=SymbolInfoDouble(S,SYMBOL_BID), ask=SymbolInfoDouble(S,SYMBOL_ASK);
   double fav=(ptype==POSITION_TYPE_BUY)?bid-entryPx:entryPx-ask;
   if(!gTP1done){
      if(InpTimeStopBars>0){ int held=(int)((lastBar-openBar)/PeriodSeconds(InpTF)); if(held>=InpTimeStopBars && fav<0.5*riskPx){ CloseMine("Time-stop"); return; } }
      if(fav>=gTP1dist && gTP1dist>0){ double cv=AdjVol(gInitVol*InpPartialPct/100.0);
         if(cv>0 && cv<pos.Volume()) trade.PositionClosePartial(tk,cv);
         double be=NormalizeDouble((ptype==POSITION_TYPE_BUY)?entryPx+InpBEOffsetR*riskPx:entryPx-InpBEOffsetR*riskPx,gDigits);
         if(pos.SelectByTicket(tk)) trade.PositionModify(tk,be,pos.TakeProfit()); gTP1done=true; }
   } else if(InpUseTrail){ double td=TrailDist(atr); if(td>0){ double csl=pos.StopLoss(),ctp=pos.TakeProfit();
      if(ptype==POSITION_TYPE_BUY){ double nsl=NormalizeDouble(bid-td,gDigits); if(nsl>csl && bid-nsl>=minStop) trade.PositionModify(tk,nsl,ctp); }
      else { double nsl=NormalizeDouble(ask+td,gDigits); if((csl==0||nsl<csl) && nsl-ask>=minStop) trade.PositionModify(tk,nsl,ctp); } } } }

//====================== OBJETIVO / DD ======================
double TargetPct(){ if(InpAccountMode==MODE_FASE1) return InpTargetP1; if(InpAccountMode==MODE_FASE2) return InpTargetP2; return 0; }
double ProfitPct(){ if(gInitBal<=0) return 0; return 100.0*(AccountInfoDouble(ACCOUNT_EQUITY)-gInitBal)/gInitBal; }
double DDFloor(){ double L=InpAcctMaxDDPct/100.0; if(InpDDType==DD_STATIC && gInitBal>0) return gInitBal*(1.0-L);
   if(InpDDType==DD_TRAIL_BE && gInitBal>0){ double f=gPeakEq-L*gInitBal; return (f>gInitBal)?gInitBal:f; } return gPeakEq*(1.0-L); }
double DDPct(){ double ref=(InpDDType==DD_STATIC && gInitBal>0)?gInitBal:gPeakEq; double eq=AccountInfoDouble(ACCOUNT_EQUITY); return (ref>0)?100.0*(ref-eq)/ref:0; }

void ComputeStats(){ stTrades=0; stWins=0; stNet=0; if(!HistorySelect(0,TimeCurrent()+3600)) return; int n=HistoryDealsTotal();
   ulong ids[]; double prof[]; for(int i=0;i<n;i++){ ulong t=HistoryDealGetTicket(i); if(t==0)continue; if(HistoryDealGetInteger(t,DEAL_MAGIC)!=InpMagic)continue; long dt=HistoryDealGetInteger(t,DEAL_TYPE); if(dt!=DEAL_TYPE_BUY&&dt!=DEAL_TYPE_SELL)continue; ulong pid=(ulong)HistoryDealGetInteger(t,DEAL_POSITION_ID);
      double dp=HistoryDealGetDouble(t,DEAL_PROFIT)+HistoryDealGetDouble(t,DEAL_SWAP)+HistoryDealGetDouble(t,DEAL_COMMISSION); int at=-1; for(int k=0;k<ArraySize(ids);k++) if(ids[k]==pid){ at=k; break; } if(at<0){ at=ArraySize(ids); ArrayResize(ids,at+1); ArrayResize(prof,at+1); ids[at]=pid; prof[at]=0; } prof[at]+=dp; }
   for(int k=0;k<ArraySize(ids);k++){ double p=prof[k]; stTrades++; stNet+=p; if(p>=0) stWins++; } stWR=stTrades>0?100.0*stWins/stTrades:0; }

//====================== NOTICIAS (Forex Factory) ======================
string QQ(){ return CharToString((uchar)34); } // comilla doble, sin escapes
int JImp(string s){ if(StringFind(s,"High")>=0) return 0; if(StringFind(s,"Medium")>=0) return 1; if(StringFind(s,"Low")>=0) return 2; return 3; }
string JVal(string rec,string key){ string q=QQ(); string k=q+key+q+":"+q; int p=StringFind(rec,k); if(p>=0){ p+=StringLen(k); int e=StringFind(rec,q,p); if(e<0) return ""; return StringSubstr(rec,p,e-p); }
   k=q+key+q+":"; p=StringFind(rec,k); if(p<0) return ""; p+=StringLen(k); int e2=StringFind(rec,",",p); if(e2<0) e2=StringFind(rec,"}",p); if(e2<0) return ""; return StringSubstr(rec,p,e2-p); }
// Convierte la fecha ISO de FF (con offset) a hora del servidor.
datetime ParseFF(string d){ if(StringLen(d)<16) return 0; MqlDateTime t; t.year=(int)StringToInteger(StringSubstr(d,0,4)); t.mon=(int)StringToInteger(StringSubstr(d,5,2)); t.day=(int)StringToInteger(StringSubstr(d,8,2)); t.hour=(int)StringToInteger(StringSubstr(d,11,2)); t.min=(int)StringToInteger(StringSubstr(d,14,2)); t.sec=0; datetime local=StructToTime(t);
   int off=0; if(StringLen(d)>=25){ int sign=(StringGetCharacter(d,19)=='-')?-1:1; int oh=(int)StringToInteger(StringSubstr(d,20,2)); int om=(int)StringToInteger(StringSubstr(d,23,2)); off=sign*(oh*3600+om*60); }
   datetime gmt=local-off; return gmt+InpServerGmt*3600; }
void FetchNews(){ nwLast=TimeCurrent(); if(!InpUseNews) return; ArrayResize(nwT,0); ArrayResize(nwImp,0); ArrayResize(nwCur,0);
   string url="https://nfs.faireconomy.media/ff_calendar_thisweek.json"; char post[]; char res[]; string rh; ResetLastError();
   int r=WebRequest("GET",url,NULL,NULL,5000,post,0,res,rh);
   if(r!=200){ nwFail=true; Print("Noticias: no se pudo leer (",r,"). Permite la URL https://nfs.faireconomy.media en Opciones > Asesores expertos."); return; }
   nwFail=false; string body=CharArrayToString(res,0,WHOLE_ARRAY,CP_UTF8); StringReplace(body,"},{","}|{"); string recs[]; int n=StringSplit(body,'|',recs);
   for(int i=0;i<n;i++){ string cur=JVal(recs[i],"country"); if(cur=="") cur=JVal(recs[i],"currency"); datetime tt=ParseFF(JVal(recs[i],"date")); if(tt<=0) continue; int ic=JImp(JVal(recs[i],"impact")); int m=ArraySize(nwT); ArrayResize(nwT,m+1); ArrayResize(nwImp,m+1); ArrayResize(nwCur,m+1); nwT[m]=tt; nwImp[m]=ic; nwCur[m]=cur; } }
bool InNews(){ if(!InpUseNews) return false; datetime now=TimeCurrent();
   for(int i=0;i<ArraySize(nwT);i++){ if(nwImp[i]>InpNewsImpact) continue; if(StringLen(InpNewsCur)>0 && StringFind(InpNewsCur,nwCur[i])<0) continue;
      if(now>=nwT[i]-InpNewsBefore*60 && now<=nwT[i]+InpNewsAfter*60) return true; } return false; }

//====================== INIT / TICK ======================
int OnInit(){ S=ResolveSymbol(InpSymbol); if(!SymbolSelect(S,true)){ Print("Simbolo no disponible: ",S); return INIT_FAILED; }
   point=SymbolInfoDouble(S,SYMBOL_POINT); gDigits=(int)SymbolInfoInteger(S,SYMBOL_DIGITS);
   long a=SymbolInfoInteger(S,SYMBOL_TRADE_STOPS_LEVEL),f2=SymbolInfoInteger(S,SYMBOL_TRADE_FREEZE_LEVEL); minStop=(double)MathMax(a,f2)*point;
   atrH=iATR(S,InpTF,InpATRPeriod);
   if(InpEntry==ENT_MA){ maF=iMA(S,InpTF,InpMAfast,0,MODE_EMA,PRICE_CLOSE); maS=iMA(S,InpTF,InpMAslow,0,MODE_EMA,PRICE_CLOSE); }
   if(InpEntry==ENT_RSI){ rsiH=iRSI(S,InpTF,InpRSIperiod,PRICE_CLOSE); }
   if(InpTrendMode==0){ trendH=iMA(S,InpTrendTF,InpTrendMA,0,MODE_EMA,PRICE_CLOSE); }
   trade.SetExpertMagicNumber(InpMagic); trade.SetTypeFillingBySymbol(S); trade.SetDeviationInPoints(20);
   curDayId=DayId(); dayStartEq=AccountInfoDouble(ACCOUNT_EQUITY); gPeakEq=AccountInfoDouble(ACCOUNT_EQUITY);
   gInitBal=(InpInitBalance>0)?InpInitBalance:AccountInfoDouble(ACCOUNT_BALANCE);
   ComputeStats(); if(InpUseNews) FetchNews(); Activate(); EventSetTimer(2); Print(${q(s.name)},"${T(' iniciado en ', ' started on ')}",S); return INIT_SUCCEEDED; }
void OnDeinit(const int reason){ EventKillTimer(); if(atrH!=INVALID_HANDLE) IndicatorRelease(atrH); if(maF!=INVALID_HANDLE) IndicatorRelease(maF); if(maS!=INVALID_HANDLE) IndicatorRelease(maS); if(rsiH!=INVALID_HANDLE) IndicatorRelease(rsiH); if(trendH!=INVALID_HANDLE) IndicatorRelease(trendH); ObjectsDeleteAll(0,PFX); }
void OnTimer(){ Engine(); Panel(); }
void OnTick(){ Engine(); Panel(); }
void DailyReset(){ int d=DayId(); if(d!=curDayId){ curDayId=d; gTradesToday=0; dayLocked=false; gDayGoal=false; dayStartEq=AccountInfoDouble(ACCOUNT_EQUITY); } }

void Engine(){ if(atrH==INVALID_HANDLE) return; DailyReset(); bool nb=NewBar(); Manage();
   if(TimeCurrent()-gAuthLastTry>3600) Activate();   // re-verifica activación cada hora
   double eq=AccountInfoDouble(ACCOUNT_EQUITY); if(eq>gPeakEq) gPeakEq=eq;
   if(TimeCurrent()%30==0) ComputeStats();
   if(InpUseNews && TimeCurrent()-nwLast>1800) FetchNews(); gInNews=InNews();
   if(ForceClose() && CountMine()>0) CloseMine("Cierre de sesion");
   if(FridayCut() && CountMine()>0) CloseMine("Fin de semana");
   // cap diario (unidad)
   if(InpDailyLossValue>0 && !dayLocked && dayStartEq>0){ double loss=dayStartEq-eq; if(loss>=DailyCapMoney()){ dayLocked=true; CloseMine("Cap diario"); } }
   // objetivo diario (unidad): deja de abrir
   if(InpDailyProfitValue>0 && dayStartEq>0 && !gDayGoal && (eq-dayStartEq)>=DailyTgtMoney()) gDayGoal=true;
   // frenos de cuenta
   bool soft=(InpAcctSoftStopPct>0 && dayStartEq>0 && 100.0*(dayStartEq-eq)/dayStartEq>=InpAcctSoftStopPct);
   bool hardDay=(InpAcctDailyStopPct>0 && dayStartEq>0 && 100.0*(dayStartEq-eq)/dayStartEq>=InpAcctDailyStopPct);
   bool totHalt=(InpAcctMaxDDPct>0 && eq<=DDFloor());
   if((hardDay||totHalt) && CountMine()>0){ CloseMine("Guardian de cuenta"); dayLocked=true; }
   if(InpHaltAtTarget && TargetPct()>0 && gInitBal>0 && !gTargetHit && ProfitPct()>=TargetPct()) gTargetHit=true;
   bool blocked = !gAuth||dayLocked||soft||gTargetHit||gDayGoal||gInNews||FridayCut()||!DayOperable()||!InWindow()||(InpMaxTradesPerDay>0 && gTradesToday>=InpMaxTradesPerDay);
   if(nb && !blocked && CountMine()==0){ int bias=TrendDir(); int sig=EntrySignal(); int dir=(InpEntry==ENT_TIME)?bias:sig;
      if(dir!=0 && (bias==0 || (dir>0?bias>0:bias<0))){ if(dir>0 && InpAllowLongs) OpenTrade(1); else if(dir<0 && InpAllowShorts) OpenTrade(-1); } }
   if(!gAuth) noReason=gAuthMsg; else if(gTargetHit) noReason="${T('Objetivo alcanzado', 'Target reached')}"; else if(dayLocked) noReason="${T('Dia bloqueado', 'Day locked')}"; else if(gInNews) noReason="${T('En noticias', 'News window')}"; else if(gDayGoal) noReason="${T('Objetivo diario hecho', 'Daily target done')}"; else if(soft) noReason="${T('Freno suave', 'Soft brake')}"; else if(!DayOperable()||FridayCut()) noReason="${T('Fuera de sesion', 'Out of session')}"; else if(!InWindow()) noReason="${T('Fuera de horario', 'Out of hours')}"; else if(CountMine()>0) noReason="${T('En operacion', 'In trade')}"; else noReason="${T('Buscando entrada', 'Seeking entry')}"; }

//====================== PANEL ======================
void L(string n,int x,int y,string txt,color c,int fs=9,bool bold=false){ string nm=PFX+n; if(ObjectFind(0,nm)<0) ObjectCreate(0,nm,OBJ_LABEL,0,0,0);
   ObjectSetInteger(0,nm,OBJPROP_XDISTANCE,x); ObjectSetInteger(0,nm,OBJPROP_YDISTANCE,y); ObjectSetString(0,nm,OBJPROP_TEXT,txt); ObjectSetInteger(0,nm,OBJPROP_COLOR,c);
   ObjectSetInteger(0,nm,OBJPROP_FONTSIZE,fs); ObjectSetString(0,nm,OBJPROP_FONT,bold?"Segoe UI Semibold":"Segoe UI"); ObjectSetInteger(0,nm,OBJPROP_CORNER,CORNER_LEFT_UPPER); ObjectSetInteger(0,nm,OBJPROP_SELECTABLE,false); ObjectSetInteger(0,nm,OBJPROP_HIDDEN,true); }
void RR(string n,int x,int y,int w,int h,color bg){ string nm=PFX+n; if(ObjectFind(0,nm)<0) ObjectCreate(0,nm,OBJ_RECTANGLE_LABEL,0,0,0);
   ObjectSetInteger(0,nm,OBJPROP_XDISTANCE,x); ObjectSetInteger(0,nm,OBJPROP_YDISTANCE,y); ObjectSetInteger(0,nm,OBJPROP_XSIZE,w); ObjectSetInteger(0,nm,OBJPROP_YSIZE,h);
   ObjectSetInteger(0,nm,OBJPROP_BGCOLOR,bg); ObjectSetInteger(0,nm,OBJPROP_BORDER_TYPE,BORDER_FLAT); ObjectSetInteger(0,nm,OBJPROP_CORNER,CORNER_LEFT_UPPER); ObjectSetInteger(0,nm,OBJPROP_BACK,false); ObjectSetInteger(0,nm,OBJPROP_SELECTABLE,false); ObjectSetInteger(0,nm,OBJPROP_HIDDEN,true); }
void Panel(){ if(!InpShowPanel) return; int X=InpPanelX,Y=InpPanelY,W=274,PAD=11,IW=W-2*PAD;
   color bg=C'24,26,32',cv=C'236,237,242',cm=C'150,153,162',cg=C'90,214,150',cr=C'236,110,110',ca=C'240,190,90',ctrk=C'44,47,56';
   int H=140; double tg0=TargetPct(); if(tg0>0) H+=27; if(InpUseNews) H+=14;
   RR("bg",X,Y,W,H,bg); int y=Y+9;
   L("t",X+PAD,y,InpComment,cv,12,true);
   int pw=88; color bc=(CountMine()>0?cg:((dayLocked||gInNews)?cr:ca)); RR("stp",X+W-PAD-pw,y-1,pw,17,C'40,43,52'); L("stpl",X+W-PAD-pw+7,y+2,noReason,bc,8,true); y+=23;
   L("firm",X+PAD,y,"${T('Empresa', 'Firm')}: "+InpFirmName+"   ·   ${T('Cuenta', 'Account')}: $"+DoubleToString(gInitBal,0),cm,9); y+=16;
   int _td=TrendDir(); L("sub",X+PAD,y,S+"   ·   ${T('sesgo', 'bias')} "+(_td>0?"${T('ALCISTA', 'UP')}":(_td<0?"${T('BAJISTA', 'DOWN')}":"${T('rango', 'range')}"))+"   ·   ${T('ops', 'trades')} "+(string)gTradesToday,cm,9); y+=18;
   double eq=AccountInfoDouble(ACCOUNT_EQUITY), bal=AccountInfoDouble(ACCOUNT_BALANCE);
   L("a",X+PAD,y,"${T('Balance', 'Balance')} $"+DoubleToString(bal,0)+"     ${T('Equity', 'Equity')} $"+DoubleToString(eq,0),cv,9); y+=17;
   double dd=DDPct(); if(dd<0)dd=0; double ddf=(InpFirmTotalLimitPct>0?dd/InpFirmTotalLimitPct:0); if(ddf>1)ddf=1; color dc=(ddf<0.5)?cg:((ddf<0.8)?ca:cr);
   L("ddl",X+PAD,y,"DD "+DoubleToString(dd,2)+"%  /  "+DoubleToString(InpFirmTotalLimitPct,0)+"%",cm,8); y+=13;
   RR("ddt",X+PAD,y,IW,6,ctrk); RR("ddf",X+PAD,y,(int)(IW*ddf),6,dc); y+=15;
   if(tg0>0){ double pp=ProfitPct(); double tf=(tg0>0?pp/tg0:0); if(tf<0)tf=0; if(tf>1)tf=1; color tc=(pp>=tg0)?cg:C'120,140,255';
      L("tgl",X+PAD,y,"${T('Objetivo', 'Target')} "+(pp>=0?"+":"")+DoubleToString(pp,2)+"%  /  "+DoubleToString(tg0,0)+"%",cm,8); y+=13;
      RR("tgt",X+PAD,y,IW,6,ctrk); RR("tgf",X+PAD,y,(int)(IW*tf),6,tc); y+=15; }
   L("s",X+PAD,y,"WR "+DoubleToString(stWR,0)+"%    ${T('Trades', 'Trades')} "+(string)stTrades+"    ${T('Neto', 'Net')} "+(stNet>=0?"+$":"-$")+DoubleToString(MathAbs(stNet),0),cv,9); y+=16;
   if(InpUseNews){ string ns=nwFail?"${T('noticias: permite la URL en Opciones', 'news: allow the URL in Options')}":(gInNews?"${T('en ventana de noticias', 'in news window')}":"${T('filtro de noticias activo', 'news filter on')}"); L("nw",X+PAD,y,"•  "+ns,gInNews?ca:cm,8); }
   ChartRedraw(); }
`;
}
