import type { BotSpec } from '@/lib/botSpec';

// ============================================================================
// Generador del cBot cTrader (.cs, cAlgo). Mismo comportamiento que MT4/MT5:
// mismas reglas, candado de activación Onyx, ventanas, días y noticias.
// Compilar en cTrader Automate y PROBAR EN DEMO. El cBot opera el símbolo del
// gráfico donde se coloca. Requiere permitir acceso a internet (FullAccess).
// ============================================================================

const b = (v: boolean) => (v ? 'true' : 'false');
const q = (s: string) => '"' + String(s).replace(/"/g, "'") + '"';
const cRisk = (u: string) => (u === 'money' ? 1 : 0);
const cU = (u: string) => ({ pips: 0, rr: 1, pct: 2, money: 3, atr: 4 } as any)[u] ?? 0;
const TFCT: Record<string, string> = {
  M1: 'Minute', M2: 'Minute2', M3: 'Minute3', M4: 'Minute4', M5: 'Minute5', M6: 'Minute6',
  M10: 'Minute10', M12: 'Minute15', M15: 'Minute15', M20: 'Minute20', M30: 'Minute30',
  H1: 'Hour', H2: 'Hour2', H3: 'Hour3', H4: 'Hour4', H6: 'Hour6', H8: 'Hour8', H12: 'Hour12',
  D1: 'Daily', W1: 'Weekly', MN1: 'Monthly',
};
const tfct = (x: string) => 'TimeFrame.' + (TFCT[x] || 'Minute5');

export function renderCT(spec: BotSpec, meta?: { userId?: string; buildId?: string; site?: string }): string {
  const s = spec;
  const en = s.botLang === 'en';
  const T = (a: string, bb: string) => (en ? bb : a);
  const site = String(meta?.site || 'https://www.onyxtradinglive.com').replace(/\/$/, '');
  const creator = String(meta?.userId || '').replace(/[^\w-]/g, '');
  const buildId = String(meta?.buildId || '').replace(/[^\w-]/g, '');
  const windowsStr = (s.windows || []).map((w) => `${w.fh * 60 + w.fm}-${w.th * 60 + w.tm}`).join(',') || `${s.signalFromH * 60 + s.signalFromM}-${s.signalToH * 60 + s.signalToM}`;
  const trig = { breakout_swing: 0, ma_cross: 1, rsi: 2, donchian: 3, time: 4 }[s.entryTrigger] ?? 1;
  const nImpact = ({ high: 0, med: 1, all: 2 } as any)[s.newsImpact] ?? 0;
  const cls = 'OnyxBot' + String(s.magic).replace(/[^0-9]/g, '');
  return `// ${s.name}  ·  ${T('generado por Onyx Bot Builder (cTrader)', 'generated by Onyx Bot Builder (cTrader)')}
// ${T('PRUEBA EN DEMO antes de real. Responsabilidad del trader.', 'TEST ON DEMO before going live. The trader is responsible.')}
using System;
using System.Globalization;
using System.Net.Http;
using System.Text;
using System.Collections.Generic;
using cAlgo.API;
using cAlgo.API.Indicators;
using cAlgo.API.Internals;

namespace cAlgo.Robots
{
    [Robot(TimeZone = TimeZones.UTC, AccessRights = AccessRights.FullAccess)]
    public class ${cls} : Robot
    {
        [Parameter("Onyx API Key", DefaultValue = "")] public string ApiKey { get; set; }

        const int    InpMagic = ${s.magic};
        const string InpComment = ${q(s.name)};
        const int    InpEntry = ${trig};
        const int    InpMAfast = 12, InpMAslow = 50, InpRSIperiod = 14, InpDonchN = 20, InpMicroSwing = ${s.microSwing}, InpEntryHour = 9;
        const double InpRSIos = 30, InpRSIob = 70;
        const int    InpTrendMode = ${s.trendMode}, InpTrendMA = 50, InpTrendSwing = 6, InpTrendDonchN = 20;
        const bool   InpAllowLongs = ${b(s.allowLongs)}, InpAllowShorts = ${b(s.allowShorts)};
        const string InpWindows = "${windowsStr}";
        const int    InpTradeDays = ${s.tradeDays ?? 62}, InpMaxTradesPerDay = ${s.maxTradesPerDay};
        const int    InpRiskUnit = ${cRisk(s.riskUnit)}, InpATRPeriod = 14;
        const double InpRiskValue = ${s.riskVal}, InpMaxLots = ${s.maxLots};
        const int    InpSLUnit = ${cU(s.slUnit)}; const double InpSLValue = ${s.slVal};
        const int    InpTP1Unit = ${cU(s.tp1Unit)}; const double InpTP1Value = ${s.tp1Val}, InpPartialPct = ${s.partialPct};
        const int    InpRunnerUnit = ${cU(s.runnerUnit)}; const double InpRunnerValue = ${s.runnerVal};
        const bool   InpUseTrail = ${b(s.useTrail)}; const int InpTrailUnit = ${cU(s.trailUnit)}; const double InpTrailValue = ${s.trailVal}, InpBEOffsetR = ${s.beOffsetR};
        const int    InpTimeStopBars = ${s.timeStopBars};
        const int    InpDailyLossUnit = ${cRisk(s.dailyLossUnit)}; const double InpDailyLossValue = ${s.dailyLossVal};
        const int    InpDailyProfitUnit = ${cRisk(s.dailyProfitUnit)}; const double InpDailyProfitValue = ${s.dailyProfitVal};
        const string InpFirmName = ${q(s.firmName)};
        const int    InpDDType = ${s.ddType}; const double InpFirmTotalLimitPct = ${s.firmTotalLimitPct};
        const double InpAcctSoftStopPct = ${s.acctSoftStopPct}, InpAcctDailyStopPct = ${s.acctDailyStopPct}, InpAcctMaxDDPct = ${s.acctMaxDDPct};
        const int    InpAccountMode = ${s.accountMode}; const double InpInitBalance = ${s.initBalance}, InpTargetP1 = ${s.targetP1}, InpTargetP2 = ${s.targetP2};
        const bool   InpHaltAtTarget = true;
        const bool   InpUseDayClose = ${b(s.useDayClose)}; const int InpForceCloseHourNY = ${s.forceCloseHourNY}, InpForceCloseMinNY = ${s.forceCloseMinNY};
        const bool   InpNoWeekend = ${b(s.noWeekend)}; const int InpFridayHour = 21;
        const bool   InpUseNews = ${b(s.useNewsFilter)}; const string InpNewsCur = ${q(s.newsCurrencies)}; const int InpNewsImpact = ${nImpact}, InpNewsBefore = ${s.newsBefore}, InpNewsAfter = ${s.newsAfter};

        const string ONYX_SITE = "${site}", ONYX_CREATOR = "${creator}", ONYX_BUILD = "${buildId}";
        readonly string Label = "OBX${s.magic}";

        Bars _eb, _tb; MovingAverage _maF, _maS, _maT; RelativeStrengthIndex _rsi; AverageTrueRange _atr;
        HttpClient _http; DateTime _lastBar = DateTime.MinValue;
        int _tradesToday = 0, _curDay = -1, _barsHeld = 0; long _curPosId = -1;
        double _dayStartEq = 0, _initBal = 0, _peakEq = 0, _entryPx = 0, _riskPx = 0, _initVol = 0, _tp1dist = 0;
        bool _dayLocked = false, _targetHit = false, _dayGoal = false, _tp1done = false, _inNews = false, _newsFail = false;
        bool _auth = false; DateTime _authLastOk = DateTime.MinValue, _authLastTry = DateTime.MinValue; string _authMsg = "${T('Verificando...', 'Checking...')}";
        List<DateTime> _nwT = new List<DateTime>(); List<int> _nwImp = new List<int>(); List<string> _nwCur = new List<string>(); DateTime _nwLast = DateTime.MinValue;
        string _noReason = "${T('Iniciando', 'Starting')}";

        protected override void OnStart()
        {
            _http = new HttpClient(); _http.Timeout = TimeSpan.FromSeconds(8);
            _eb = MarketData.GetBars(${tfct(s.tf)});
            _tb = MarketData.GetBars(${tfct(s.trendTF)});
            if (InpEntry == 1) { _maF = Indicators.MovingAverage(_eb.ClosePrices, InpMAfast, MovingAverageType.Exponential); _maS = Indicators.MovingAverage(_eb.ClosePrices, InpMAslow, MovingAverageType.Exponential); }
            if (InpEntry == 2) _rsi = Indicators.RelativeStrengthIndex(_eb.ClosePrices, InpRSIperiod);
            if (InpTrendMode == 0) _maT = Indicators.MovingAverage(_tb.ClosePrices, InpTrendMA, MovingAverageType.Exponential);
            _atr = Indicators.AverageTrueRange(_eb, InpATRPeriod, MovingAverageType.Simple);
            _curDay = Server.Time.DayOfYear; _dayStartEq = Account.Equity; _peakEq = Account.Equity;
            _initBal = InpInitBalance > 0 ? InpInitBalance : Account.Balance;
            _lastBar = _eb.OpenTimes.LastValue;
            if (InpUseNews) FetchNews(); Activate(); Timer.Start(2);
        }
        protected override void OnStop() { Chart.RemoveObject("onyx_p"); }
        protected override void OnTimer() { Engine(); Panel(); }
        protected override void OnTick() { Engine(); Panel(); }

        void Activate()
        {
            _authLastTry = Server.TimeInUtc;
            if (string.IsNullOrEmpty(ApiKey) || ApiKey.Length < 8) { _auth = false; _authMsg = "${T('Pega tu clave Onyx', 'Paste your Onyx key')}"; return; }
            try {
                var sb = new StringBuilder();
                sb.Append("{\\"key\\":\\"").Append(ApiKey).Append("\\",\\"account\\":").Append(Account.Number)
                  .Append(",\\"magic\\":").Append(InpMagic).Append(",\\"build\\":\\"").Append(ONYX_BUILD).Append("\\",\\"creator\\":\\"").Append(ONYX_CREATOR).Append("\\"}");
                var content = new StringContent(sb.ToString(), Encoding.UTF8, "application/json");
                var res = _http.PostAsync(ONYX_SITE + "/api/v1/activate", content).Result;
                var body = res.Content.ReadAsStringAsync().Result;
                if (!res.IsSuccessStatusCode) { if (_authLastOk != DateTime.MinValue && (Server.TimeInUtc - _authLastOk).TotalHours < 72) { _authMsg = "${T('Sin conexion (gracia)', 'Offline (grace)')}"; return; } _auth = false; _authMsg = "${T('Permite el acceso a internet del cBot', 'Allow the cBot internet access')}"; return; }
                if (body.IndexOf("\\"allowed\\":true", StringComparison.Ordinal) >= 0) { _auth = true; _authLastOk = Server.TimeInUtc; _authMsg = "${T('Activo', 'Active')}"; }
                else { _auth = false; _authMsg = "${T('Clave/plan no activo', 'Key/plan not active')}"; }
            } catch { if (_authLastOk != DateTime.MinValue && (Server.TimeInUtc - _authLastOk).TotalHours < 72) { _authMsg = "${T('Sin conexion (gracia)', 'Offline (grace)')}"; return; } _auth = false; _authMsg = "${T('Sin conexion', 'Offline')}"; }
        }

        int RefMin() { return Server.Time.Hour * 60 + Server.Time.Minute; }
        int RefDow() { return (int)Server.Time.DayOfWeek; }
        bool InRange(int m, int f, int t) { return (f <= t) ? (m >= f && m <= t) : (m >= f || m <= t); }
        bool InWindow() { int m = RefMin(); if (InpWindows.Length < 3) return true;
            foreach (var part in InpWindows.Split(',')) { var ab = part.Split('-'); if (ab.Length == 2) { int f, t; if (int.TryParse(ab[0], out f) && int.TryParse(ab[1], out t) && InRange(m, f, t)) return true; } } return false; }
        bool DayOperable() { return ((InpTradeDays >> RefDow()) & 1) == 1; }
        bool ForceClose() { if (!InpUseDayClose) return false; return RefMin() >= InpForceCloseHourNY * 60 + InpForceCloseMinNY; }
        bool FridayCut() { if (!InpNoWeekend) return false; if (RefDow() != 5) return false; return RefMin() >= InpFridayHour * 60; }

        double PipSz() { return Symbol.PipSize; }
        double Atr() { return _atr.Result.Last(1); }
        double UnitDist(int unit, double val, double bas, double units, double atr) {
            if (val <= 0) return 0;
            if (unit == 0) return val * PipSz();
            if (unit == 4) return val * atr;
            if (unit == 2) return Symbol.Bid * val / 100.0;
            if (unit == 1) return val * bas;
            double ts = Symbol.TickSize, tv = Symbol.TickValue; if (ts <= 0 || tv <= 0 || units <= 0) return (bas > 0 ? val * bas : val * atr); return val * ts / (units * tv); }
        double SLdist(double atr) { double d = UnitDist(InpSLUnit, InpSLValue, atr, 0, atr); if (d <= 0) d = (atr > 0 ? atr : PipSz() * 10); return d; }
        double TPdist(double sl, double units, int unit, double val, double atr) { double d = UnitDist(unit, val, sl, units, atr); if (d <= 0) d = sl * 2.0; return d; }
        double TrailDist(double atr) { double d = UnitDist(InpTrailUnit, InpTrailValue, _riskPx, _initVol, atr); if (d <= 0) d = atr; return d; }
        double RiskMoney() { if (InpSLUnit == 3) return InpSLValue; if (InpRiskUnit == 1) return InpRiskValue; return Account.Equity * InpRiskValue / 100.0; }
        double DailyCap() { if (InpDailyLossUnit == 1) return InpDailyLossValue; return _dayStartEq * InpDailyLossValue / 100.0; }
        double DailyTgt() { if (InpDailyProfitUnit == 1) return InpDailyProfitValue; return _dayStartEq * InpDailyProfitValue / 100.0; }

        int TrendDir() {
            if (InpTrendMode == 0) { double m = _maT.Result.Last(0); double px = Symbol.Bid; return px > m ? 1 : (px < m ? -1 : 0); }
            if (InpTrendMode == 2) { int N = InpTrendDonchN < 2 ? 2 : InpTrendDonchN; double hh = -1e18, ll = 1e18; for (int i = 1; i <= N; i++) { double h = _tb.HighPrices.Last(i), l = _tb.LowPrices.Last(i); if (h > hh) hh = h; if (l < ll) ll = l; } double mid = (hh + ll) / 2.0, px = Symbol.Bid; return px > mid ? 1 : (px < mid ? -1 : 0); }
            int k = InpTrendSwing < 1 ? 1 : InpTrendSwing; double[] sh = new double[2]; double[] sl = new double[2]; int nh = 0, nl = 0;
            for (int i = k + 1; i <= 250 - k - 1 && (nh < 2 || nl < 2); i++) { bool isH = true, isL = true;
                for (int j = 1; j <= k; j++) { if (_tb.HighPrices.Last(i) <= _tb.HighPrices.Last(i - j) || _tb.HighPrices.Last(i) <= _tb.HighPrices.Last(i + j)) isH = false; if (_tb.LowPrices.Last(i) >= _tb.LowPrices.Last(i - j) || _tb.LowPrices.Last(i) >= _tb.LowPrices.Last(i + j)) isL = false; if (!isH && !isL) break; }
                if (isH && nh < 2) { sh[nh] = _tb.HighPrices.Last(i); nh++; } if (isL && nl < 2) { sl[nl] = _tb.LowPrices.Last(i); nl++; } }
            if (nh < 2 || nl < 2) return 0; if (sh[0] > sh[1] && sl[0] > sl[1]) return 1; if (sh[0] < sh[1] && sl[0] < sl[1]) return -1; return 0; }
        int EntrySignal() {
            if (InpEntry == 1) { double f1 = _maF.Result.Last(1), f2 = _maF.Result.Last(2), s1 = _maS.Result.Last(1), s2 = _maS.Result.Last(2); if (f2 <= s2 && f1 > s1) return 1; if (f2 >= s2 && f1 < s1) return -1; return 0; }
            if (InpEntry == 2) { double v1 = _rsi.Result.Last(1), v2 = _rsi.Result.Last(2); if (v2 <= InpRSIos && v1 > InpRSIos) return 1; if (v2 >= InpRSIob && v1 < InpRSIob) return -1; return 0; }
            if (InpEntry == 3) { int N = InpDonchN < 2 ? 2 : InpDonchN; double hh = -1e18, ll = 1e18; for (int i = 1; i <= N; i++) { double h = _eb.HighPrices.Last(i), l = _eb.LowPrices.Last(i); if (h > hh) hh = h; if (l < ll) ll = l; } double c = _eb.ClosePrices.Last(0); if (c > hh) return 1; if (c < ll) return -1; return 0; }
            if (InpEntry == 4) { if (Server.Time.Hour == InpEntryHour && Server.Time.Minute < 5) return 1; return 0; }
            int k = InpMicroSwing < 1 ? 1 : InpMicroSwing; double hi = 0, lo = 0;
            for (int i = k + 1; i <= 110 - k - 1; i++) { bool isH = true; for (int j = 1; j <= k; j++) if (_eb.HighPrices.Last(i) <= _eb.HighPrices.Last(i - j) || _eb.HighPrices.Last(i) <= _eb.HighPrices.Last(i + j)) { isH = false; break; } if (isH) { hi = _eb.HighPrices.Last(i); break; } }
            for (int i2 = k + 1; i2 <= 110 - k - 1; i2++) { bool isL = true; for (int j2 = 1; j2 <= k; j2++) if (_eb.LowPrices.Last(i2) >= _eb.LowPrices.Last(i2 - j2) || _eb.LowPrices.Last(i2) >= _eb.LowPrices.Last(i2 + j2)) { isL = false; break; } if (isL) { lo = _eb.LowPrices.Last(i2); break; } }
            double c1 = _eb.ClosePrices.Last(1); if (hi > 0 && c1 > hi) return 1; if (lo > 0 && c1 < lo) return -1; return 0; }

        Position Mine() { foreach (var p in Positions) if (p.Label == Label && p.SymbolName == SymbolName) return p; return null; }
        int CountMine() { int n = 0; foreach (var p in Positions) if (p.Label == Label && p.SymbolName == SymbolName) n++; return n; }
        void CloseMine() { var snap = new List<Position>(Positions); foreach (var p in snap) if (p.Label == Label && p.SymbolName == SymbolName) ClosePosition(p); }
        double CalcUnits(double slDist) { if (slDist <= 0) return 0; double ts = Symbol.TickSize, tv = Symbol.TickValue; if (ts <= 0 || tv <= 0) return 0;
            double units = RiskMoney() / ((slDist / ts) * tv); double maxU = Symbol.QuantityToVolumeInUnits(InpMaxLots);
            if (units > maxU) units = maxU; units = Symbol.NormalizeVolumeInUnits(units, RoundingMode.Down);
            if (units < Symbol.VolumeInUnitsMin) units = Symbol.VolumeInUnitsMin; if (units > Symbol.VolumeInUnitsMax) units = Symbol.VolumeInUnitsMax; return units; }
        double Round(double p) { return Math.Round(p, Symbol.Digits); }
        void OpenTrade(int dir) { double atr = Atr(); if (atr <= 0) return; double slDist = SLdist(atr); if (atr > 0 && slDist < 0.2 * atr) slDist = 0.2 * atr;
            double units = CalcUnits(slDist); if (units <= 0) return;
            double runDist = TPdist(slDist, units, InpRunnerUnit, InpRunnerValue, atr); if (runDist < slDist) runDist = slDist * 2.0;
            double entry = dir > 0 ? Symbol.Ask : Symbol.Bid; double sl = dir > 0 ? entry - slDist : entry + slDist; double tp = dir > 0 ? entry + runDist : entry - runDist;
            var tr = ExecuteMarketOrder(dir > 0 ? TradeType.Buy : TradeType.Sell, SymbolName, units, Label);
            if (tr != null && tr.IsSuccessful) { ModifyPosition(tr.Position, Round(sl), Round(tp)); _tradesToday++; _tp1done = false; } }
        void Manage() { var pos = Mine(); if (pos == null) { _curPosId = -1; _tp1done = false; return; }
            double atr = Atr();
            if (pos.Id != _curPosId) { _curPosId = pos.Id; _entryPx = pos.EntryPrice; _initVol = pos.VolumeInUnits; _barsHeld = 0;
                double sl0 = pos.StopLoss ?? 0; _riskPx = sl0 > 0 ? Math.Abs(_entryPx - sl0) : SLdist(atr); if (_riskPx <= 0) _riskPx = (atr > 0 ? atr : PipSz() * 10);
                _tp1dist = TPdist(_riskPx, _initVol, InpTP1Unit, InpTP1Value, atr); if (_tp1dist <= 0) _tp1dist = _riskPx; _tp1done = false; }
            double fav = pos.TradeType == TradeType.Buy ? Symbol.Bid - _entryPx : _entryPx - Symbol.Ask;
            if (!_tp1done) {
                if (InpTimeStopBars > 0 && _barsHeld >= InpTimeStopBars && fav < 0.5 * _riskPx) { ClosePosition(pos); return; }
                if (fav >= _tp1dist && _tp1dist > 0) {
                    double cu = Symbol.NormalizeVolumeInUnits(_initVol * InpPartialPct / 100.0, RoundingMode.Down);
                    if (cu >= Symbol.VolumeInUnitsMin && cu < pos.VolumeInUnits) ClosePosition(pos, cu);
                    var p2 = Mine(); if (p2 != null) { double be = pos.TradeType == TradeType.Buy ? _entryPx + InpBEOffsetR * _riskPx : _entryPx - InpBEOffsetR * _riskPx; ModifyPosition(p2, Round(be), p2.TakeProfit); }
                    _tp1done = true; }
            } else if (InpUseTrail) { double td = TrailDist(atr); if (td > 0) { double csl = pos.StopLoss ?? 0;
                if (pos.TradeType == TradeType.Buy) { double nsl = Round(Symbol.Bid - td); if (nsl > csl) ModifyPosition(pos, nsl, pos.TakeProfit); }
                else { double nsl = Round(Symbol.Ask + td); if (csl == 0 || nsl < csl) ModifyPosition(pos, nsl, pos.TakeProfit); } } } }

        double TargetPct() { if (InpAccountMode == 0) return InpTargetP1; if (InpAccountMode == 1) return InpTargetP2; return 0; }
        double ProfitPct() { if (_initBal <= 0) return 0; return 100.0 * (Account.Equity - _initBal) / _initBal; }
        double DDFloor() { double L = InpAcctMaxDDPct / 100.0; if (InpDDType == 1 && _initBal > 0) return _initBal * (1.0 - L); if (InpDDType == 2 && _initBal > 0) { double f = _peakEq - L * _initBal; return f > _initBal ? _initBal : f; } return _peakEq * (1.0 - L); }
        double DDPct() { double refv = (InpDDType == 1 && _initBal > 0) ? _initBal : _peakEq; double eq = Account.Equity; return refv > 0 ? 100.0 * (refv - eq) / refv : 0; }

        int JImp(string s2) { if (s2.IndexOf("High", StringComparison.Ordinal) >= 0) return 0; if (s2.IndexOf("Medium", StringComparison.Ordinal) >= 0) return 1; if (s2.IndexOf("Low", StringComparison.Ordinal) >= 0) return 2; return 3; }
        string JVal(string rec, string key) { string k = "\\"" + key + "\\":\\""; int p = rec.IndexOf(k, StringComparison.Ordinal); if (p >= 0) { p += k.Length; int e = rec.IndexOf("\\"", p, StringComparison.Ordinal); if (e < 0) return ""; return rec.Substring(p, e - p); }
            k = "\\"" + key + "\\":"; p = rec.IndexOf(k, StringComparison.Ordinal); if (p < 0) return ""; p += k.Length; int e2 = rec.IndexOf(",", p, StringComparison.Ordinal); if (e2 < 0) e2 = rec.IndexOf("}", p, StringComparison.Ordinal); if (e2 < 0) return ""; return rec.Substring(p, e2 - p); }
        DateTime ParseFF(string d) { DateTime dt; if (DateTime.TryParse(d, null, DateTimeStyles.AdjustToUniversal | DateTimeStyles.AssumeUniversal, out dt)) return dt.ToUniversalTime(); return DateTime.MinValue; }
        void FetchNews() { _nwLast = Server.TimeInUtc; if (!InpUseNews) return; _nwT.Clear(); _nwImp.Clear(); _nwCur.Clear();
            try { string body = _http.GetStringAsync("https://nfs.faireconomy.media/ff_calendar_thisweek.json").Result; body = body.Replace("},{", "}|{");
                foreach (var rec in body.Split('|')) { string cur = JVal(rec, "country"); if (cur == "") cur = JVal(rec, "currency"); DateTime tt = ParseFF(JVal(rec, "date")); if (tt == DateTime.MinValue) continue; _nwT.Add(tt); _nwImp.Add(JImp(JVal(rec, "impact"))); _nwCur.Add(cur); } _newsFail = false;
            } catch { _newsFail = true; } }
        bool InNews() { if (!InpUseNews) return false; DateTime now = Server.TimeInUtc;
            for (int i = 0; i < _nwT.Count; i++) { if (_nwImp[i] > InpNewsImpact) continue; if (InpNewsCur.Length > 0 && InpNewsCur.IndexOf(_nwCur[i], StringComparison.Ordinal) < 0) continue;
                if (now >= _nwT[i].AddMinutes(-InpNewsBefore) && now <= _nwT[i].AddMinutes(InpNewsAfter)) return true; } return false; }

        void Engine() {
            if (Server.Time.DayOfYear != _curDay) { _curDay = Server.Time.DayOfYear; _tradesToday = 0; _dayLocked = false; _dayGoal = false; _dayStartEq = Account.Equity; }
            bool nb = false; DateTime bt = _eb.OpenTimes.LastValue; if (bt != _lastBar) { _lastBar = bt; nb = true; if (Mine() != null) _barsHeld++; }
            Manage();
            if ((Server.TimeInUtc - _authLastTry).TotalMinutes > 60) Activate();
            double eq = Account.Equity; if (eq > _peakEq) _peakEq = eq;
            if (InpUseNews && (Server.TimeInUtc - _nwLast).TotalMinutes > 30) FetchNews(); _inNews = InNews();
            if (ForceClose() && CountMine() > 0) CloseMine();
            if (FridayCut() && CountMine() > 0) CloseMine();
            if (InpDailyLossValue > 0 && !_dayLocked && _dayStartEq > 0 && (_dayStartEq - eq) >= DailyCap()) { _dayLocked = true; CloseMine(); }
            if (InpDailyProfitValue > 0 && _dayStartEq > 0 && !_dayGoal && (eq - _dayStartEq) >= DailyTgt()) _dayGoal = true;
            bool soft = InpAcctSoftStopPct > 0 && _dayStartEq > 0 && 100.0 * (_dayStartEq - eq) / _dayStartEq >= InpAcctSoftStopPct;
            bool hardDay = InpAcctDailyStopPct > 0 && _dayStartEq > 0 && 100.0 * (_dayStartEq - eq) / _dayStartEq >= InpAcctDailyStopPct;
            bool totHalt = InpAcctMaxDDPct > 0 && eq <= DDFloor();
            if ((hardDay || totHalt) && CountMine() > 0) { CloseMine(); _dayLocked = true; }
            if (InpHaltAtTarget && TargetPct() > 0 && _initBal > 0 && !_targetHit && ProfitPct() >= TargetPct()) _targetHit = true;
            bool blocked = !_auth || _dayLocked || soft || _targetHit || _dayGoal || _inNews || FridayCut() || !DayOperable() || !InWindow() || (InpMaxTradesPerDay > 0 && _tradesToday >= InpMaxTradesPerDay);
            if (nb && !blocked && CountMine() == 0) { int bias = TrendDir(); int sig = EntrySignal(); int dir = InpEntry == 4 ? bias : sig;
                if (dir != 0 && (bias == 0 || (dir > 0 ? bias > 0 : bias < 0))) { if (dir > 0 && InpAllowLongs) OpenTrade(1); else if (dir < 0 && InpAllowShorts) OpenTrade(-1); } }
            if (!_auth) _noReason = _authMsg; else if (_targetHit) _noReason = "${T('Objetivo alcanzado', 'Target reached')}"; else if (_dayLocked) _noReason = "${T('Dia bloqueado', 'Day locked')}"; else if (_inNews) _noReason = "${T('En noticias', 'News window')}"; else if (_dayGoal) _noReason = "${T('Objetivo diario hecho', 'Daily target done')}"; else if (soft) _noReason = "${T('Freno suave', 'Soft brake')}"; else if (!DayOperable() || FridayCut()) _noReason = "${T('Fuera de sesion', 'Out of session')}"; else if (!InWindow()) _noReason = "${T('Fuera de horario', 'Out of hours')}"; else if (CountMine() > 0) _noReason = "${T('En operacion', 'In trade')}"; else _noReason = "${T('Buscando entrada', 'Seeking entry')}"; }

        void Panel() {
            int bias = TrendDir(); string bs = bias > 0 ? "${T('ALCISTA', 'UP')}" : (bias < 0 ? "${T('BAJISTA', 'DOWN')}" : "${T('rango', 'range')}");
            string txt = InpComment + "   [" + _noReason + "]\\n"
                + "${T('Empresa', 'Firm')}: " + InpFirmName + "   ${T('sesgo', 'bias')}: " + bs + "   ${T('ops', 'trades')}: " + _tradesToday + "\\n"
                + "${T('Balance', 'Balance')} " + Account.Balance.ToString("F0") + "   ${T('Equity', 'Equity')} " + Account.Equity.ToString("F0") + "   DD " + DDPct().ToString("F2") + "%/" + InpFirmTotalLimitPct.ToString("F0") + "%";
            if (TargetPct() > 0) txt += "\\n${T('Objetivo', 'Target')} " + ProfitPct().ToString("F2") + "%/" + TargetPct().ToString("F0") + "%";
            if (InpUseNews) txt += _newsFail ? "\\n${T('noticias: permite el acceso a internet', 'news: allow internet access')}" : (_inNews ? "\\n${T('en ventana de noticias', 'in news window')}" : "");
            Chart.DrawStaticText("onyx_p", txt, VerticalAlignment.Top, HorizontalAlignment.Left, Color.FromArgb(255, 220, 224, 235));
        }
    }
}
`;
}
